package pwmsg

import (
	"bytes"
	"fmt"
	"go/format"
	"sort"
	"strconv"
	"strings"
	"unicode"
)

const (
	pwPackage      = "github.com/shibukawa/popcornwave/pw"
	runtimePackage = "github.com/shibukawa/popcornwave/pwruntime"
	htmlbindImport = "github.com/shibukawa/tinybind-go/htmlbind"
)

// Symbol is what one resolved message ID calls. It is the downstream half of
// the table system:tinybind is given, per decision:upstream-message-surface.
type Symbol struct {
	// Name is the exported Go function.
	Name string
	// Params are the argument names in declaration order, excluding the leading
	// locale the implicit binding supplies.
	Params []string
	// Rich marks a message whose function returns segments rather than a
	// string.
	Rich bool
}

// Generated is the output of one generation run.
type Generated struct {
	// Source is the formatted Go file.
	Source []byte
	// Symbols maps a resolved message ID to the symbol a reference calls.
	Symbols map[string]Symbol
}

// Generate emits the message package for a catalog.
//
// packageName is the Go package the file is written into. Every table is data
// and every function is code, so adding a locale grows the file by rows and not
// by functions. See .knowledge decision:message-code-shape.
func Generate(catalog *Catalog, packageName string) (*Generated, error) {
	if len(catalog.Locales) == 0 {
		return nil, fmt.Errorf("no locales declared")
	}
	messages, err := collect(catalog)
	if err != nil {
		return nil, err
	}

	var body bytes.Buffer
	symbols := make(map[string]Symbol, len(messages))
	needsRich := false
	needsRender := false
	helpers := map[string]bool{}

	for _, message := range messages {
		symbols[message.ID] = Symbol{Name: message.Symbol, Params: message.ParamNames(), Rich: message.Entry.Rich}
		if message.Entry.Rich {
			needsRich = true
		}
		if len(message.Entry.Params) > 0 {
			needsRender = true
		}
		if message.Entry.Plural != "" {
			for _, tag := range catalog.Locales {
				if rule, _ := RuleFor(tag); rule.Selector != "" {
					if name := helperName(rule.Selector); name != "" {
						helpers[name] = true
					}
				}
			}
		}
		if err := emitMessage(&body, catalog, message); err != nil {
			return nil, err
		}
	}

	var file bytes.Buffer
	fmt.Fprintf(&file, "// Code generated by pw generate. DO NOT EDIT.\n\npackage %s\n\n", packageName)

	imports := []string{strconv.Quote(pwPackage), strconv.Quote(runtimePackage)}
	if needsRich {
		imports = append(imports, strconv.Quote(htmlbindImport))
	}
	fmt.Fprintf(&file, "import (\n%s\n)\n\n", strings.Join(imports, "\n"))

	emitRegistration(&file, catalog)
	emitPluralSelectors(&file, catalog, helpers)
	file.Write(body.Bytes())

	// pw and pwruntime are both referenced by every generated signature and
	// every table, but a catalog with no argument-taking message never calls
	// the renderer, and the compiler would then reject the import.
	if !needsRender && !needsRich {
		fmt.Fprintf(&file, "\nvar _ = pwruntime.RenderMessage\n")
	}

	source, err := format.Source(file.Bytes())
	if err != nil {
		return nil, fmt.Errorf("generated message package does not parse: %w\n%s", err, file.String())
	}
	return &Generated{Source: source, Symbols: symbols}, nil
}

// message is one entry paired with its resolved identity.
type message struct {
	ID     string
	Symbol string
	Scope  string
	Entry  Entry
	// Var is the unexported table variable name.
	Var string
}

func (m message) ParamNames() []string {
	names := make([]string, len(m.Entry.Params))
	for i, param := range m.Entry.Params {
		names[i] = param.Name
	}
	return names
}

func collect(catalog *Catalog) ([]message, error) {
	var messages []message
	bySymbol := map[string]string{}
	for _, scope := range catalog.Scopes {
		for _, entry := range scope.Entries {
			id := entry.Qualified(scope.Name)
			symbol := goSymbol(id)
			if previous, clash := bySymbol[symbol]; clash {
				return nil, fmt.Errorf("messages %q and %q both become Go symbol %s; rename one, since the mapping from ID to symbol has to stay one to one", previous, id, symbol)
			}
			bySymbol[symbol] = id
			messages = append(messages, message{
				ID:     id,
				Symbol: symbol,
				Scope:  scope.Name,
				Entry:  entry,
				Var:    "tbl" + symbol,
			})
		}
	}
	sort.Slice(messages, func(i, j int) bool { return messages[i].ID < messages[j].ID })
	return messages, nil
}

func emitRegistration(out *bytes.Buffer, catalog *Catalog) {
	fmt.Fprintf(out, "// Declared locales, in declaration order. The index of each is the subscript\n// of every table below.\nvar (\n")
	for i, tag := range catalog.Locales {
		fmt.Fprintf(out, "\t%s = pwruntime.NewLocale(%s, %d)\n", localeConst(tag), strconv.Quote(tag), i)
	}
	fmt.Fprintf(out, ")\n\n")

	quoted := make([]string, len(catalog.Locales))
	for i, tag := range catalog.Locales {
		quoted[i] = strconv.Quote(tag)
	}
	fmt.Fprintf(out, "func init() {\n\tpwruntime.RegisterLocales([]string{%s}, %s)\n",
		strings.Join(quoted, ", "), strconv.Quote(catalog.Default))

	var routes []string
	for _, route := range catalog.Routing.Routes {
		routes = append(routes, fmt.Sprintf("{Prefix: %s, Mode: pwruntime.LocaleMode%s}",
			strconv.Quote(route.Prefix), strings.ToUpper(route.Mode[:1])+route.Mode[1:]))
	}
	labelTags := make([]string, 0, len(catalog.Routing.Labels))
	for tag := range catalog.Routing.Labels {
		labelTags = append(labelTags, tag)
	}
	sort.Strings(labelTags)
	var labels []string
	for _, tag := range labelTags {
		labels = append(labels, fmt.Sprintf("%s: %s", strconv.Quote(tag), strconv.Quote(catalog.Routing.Labels[tag])))
	}
	fmt.Fprintf(out, "\tpwruntime.RegisterLocaleRouting(\n\t\t[]pwruntime.LocaleRoute{%s},\n\t\tmap[string]string{%s},\n\t\t%t,\n\t)\n}\n\n",
		strings.Join(routes, ", "), strings.Join(labels, ", "), catalog.Routing.PrefixDefault)
}

// emitPluralSelectors writes the per-locale category selector and only the
// helpers the declared locales reach, so a project with no Slavic locale carries
// none of that arithmetic.
func emitPluralSelectors(out *bytes.Buffer, catalog *Catalog, helpers map[string]bool) {
	if len(helpers) == 0 && !anyPlural(catalog) {
		return
	}
	fmt.Fprintf(out, "// pluralIndex reports the position of the matching plural form within the\n// locale's own variant list, which is how a table row is addressed.\nfunc pluralIndex(loc pw.Locale, n int) int {\n\tswitch loc.Index() {\n")
	for i, tag := range catalog.Locales {
		rule, _ := RuleFor(tag)
		selector := rule.Selector
		if selector == "" {
			selector = "return 0"
		}
		fmt.Fprintf(out, "\tcase %d: // %s\n%s\n", i, tag, selector)
	}
	fmt.Fprintf(out, "\t}\n\treturn 0\n}\n\n")

	names := make([]string, 0, len(helpers))
	for name := range helpers {
		names = append(names, name)
	}
	sort.Strings(names)
	for _, name := range names {
		fmt.Fprintf(out, "%s\n\n", pluralHelpers[name])
	}
}

func anyPlural(catalog *Catalog) bool {
	for _, scope := range catalog.Scopes {
		for _, entry := range scope.Entries {
			if entry.Plural != "" {
				return true
			}
		}
	}
	return false
}

func emitMessage(out *bytes.Buffer, catalog *Catalog, m message) error {
	rows, err := buildRows(catalog, m)
	if err != nil {
		return err
	}
	signature, argExprs, err := signatureOf(m)
	if err != nil {
		return err
	}

	switch {
	case m.Entry.Rich:
		emitTable(out, m.Var, "[]pwruntime.RichSegment", rows, catalog.Locales, m.Entry.Plural != "")
		fmt.Fprintf(out, "// %s renders message %q.\nfunc %s(%s) []htmlbind.MessageSegment {\n", m.Symbol, m.ID, m.Symbol, signature)
		fmt.Fprintf(out, "\treturn pwruntime.RenderRichMessage(%s%s)\n}\n\n", rowExpr(m), argsSuffix(argExprs))
	case len(m.Entry.Params) == 0:
		emitTable(out, m.Var, "string", rows, catalog.Locales, false)
		fmt.Fprintf(out, "// %s renders message %q.\nfunc %s(%s) string {\n\treturn %s[loc.Index()]\n}\n\n",
			m.Symbol, m.ID, m.Symbol, signature, m.Var)
	default:
		emitTable(out, m.Var, "[]pwruntime.Segment", rows, catalog.Locales, m.Entry.Plural != "")
		fmt.Fprintf(out, "// %s renders message %q.\nfunc %s(%s) string {\n", m.Symbol, m.ID, m.Symbol, signature)
		fmt.Fprintf(out, "\treturn pwruntime.RenderMessage(%s%s)\n}\n\n", rowExpr(m), argsSuffix(argExprs))
	}
	return nil
}

func rowExpr(m message) string {
	if m.Entry.Plural != "" {
		return fmt.Sprintf("%s[loc.Index()][pluralIndex(loc, %s)]", m.Var, m.Entry.Plural)
	}
	return fmt.Sprintf("%s[loc.Index()]", m.Var)
}

func argsSuffix(args []string) string {
	if len(args) == 0 {
		return ""
	}
	return ", " + strings.Join(args, ", ")
}

// signatureOf builds the Go parameter list and the expressions converting each
// argument to the string the renderer takes.
func signatureOf(m message) (string, []string, error) {
	parts := []string{"loc pw.Locale"}
	var args []string
	for _, param := range m.Entry.Params {
		parts = append(parts, fmt.Sprintf("%s %s", param.Name, param.Type))
		switch param.Type {
		case "string":
			args = append(args, param.Name)
		case "int":
			args = append(args, fmt.Sprintf("pwruntime.FormatInt(loc, %s)", param.Name))
		default:
			return "", nil, fmt.Errorf("message %q parameter %q has type %s; this generator renders string and int, and a wider set needs a formatting rule per type rather than a fmt call that would pull reflection into every build",
				m.ID, param.Name, param.Type)
		}
	}
	return strings.Join(parts, ", "), args, nil
}

// emitTable writes one table. A plural table gains a second dimension whose
// order is the locale's own category list, which is what pluralIndex reports a
// position into.
func emitTable(out *bytes.Buffer, name, elem string, rows map[string][]string, locales []string, plural bool) {
	if plural {
		fmt.Fprintf(out, "var %s = [...][]%s{\n", name, elem)
	} else {
		fmt.Fprintf(out, "var %s = [...]%s{\n", name, elem)
	}
	for _, tag := range locales {
		forms := rows[tag]
		if plural {
			fmt.Fprintf(out, "\t{%s}, // %s\n", strings.Join(forms, ", "), tag)
			continue
		}
		fmt.Fprintf(out, "\t%s, // %s\n", forms[0], tag)
	}
	fmt.Fprintf(out, "}\n\n")
}

// buildRows renders each locale's table entry, resolving the fallback chain at
// generation so no row is empty and no runtime fallback branch exists.
func buildRows(catalog *Catalog, m message) (map[string][]string, error) {
	rows := map[string][]string{}
	index := map[string]int{}
	for i, param := range m.Entry.Params {
		index[param.Name] = i + 1
	}
	for _, tag := range catalog.Locales {
		text, ok := resolveText(catalog, m.Entry, tag)
		if !ok {
			return nil, fmt.Errorf("message %q has no translation for %q and none in its fallback chain", m.ID, tag)
		}
		var forms []string
		for _, body := range textForms(text) {
			pieces, err := ParseText(body, m.Entry.Rich)
			if err != nil {
				return nil, fmt.Errorf("message %q locale %q: %w", m.ID, tag, err)
			}
			switch {
			case m.Entry.Rich:
				forms = append(forms, richLiteral(pieces, index))
			case len(m.Entry.Params) == 0:
				forms = append(forms, strconv.Quote(literalText(pieces)))
			default:
				forms = append(forms, segmentLiteral(pieces, index))
			}
		}
		rows[tag] = forms
	}
	return rows, nil
}

// resolveText walks the fallback chain: the locale itself, then its base
// language, then the declared default. The chain is static, so it is walked here
// rather than at render.
func resolveText(catalog *Catalog, entry Entry, tag string) (Text, bool) {
	if text, ok := entry.Texts[tag]; ok {
		return text, true
	}
	if base := baseLanguage(tag); base != tag {
		if text, ok := entry.Texts[base]; ok {
			return text, true
		}
	}
	if text, ok := entry.Texts[catalog.Default]; ok {
		return text, true
	}
	return Text{}, false
}

func literalText(pieces []Piece) string {
	var out strings.Builder
	for _, piece := range pieces {
		out.WriteString(piece.Lit)
	}
	return out.String()
}

func segmentLiteral(pieces []Piece, index map[string]int) string {
	parts := make([]string, 0, len(pieces))
	for _, piece := range pieces {
		if piece.Arg != "" {
			parts = append(parts, fmt.Sprintf("{Arg: %d}", index[piece.Arg]))
			continue
		}
		parts = append(parts, fmt.Sprintf("{Lit: %s}", strconv.Quote(piece.Lit)))
	}
	return "{" + strings.Join(parts, ", ") + "}"
}

func richLiteral(pieces []Piece, index map[string]int) string {
	parts := make([]string, 0, len(pieces))
	for _, piece := range pieces {
		fields := []string{}
		if piece.Hole != "" {
			fields = append(fields, fmt.Sprintf("Hole: %s", strconv.Quote(piece.Hole)))
		}
		if piece.Arg != "" {
			fields = append(fields, fmt.Sprintf("Arg: %d", index[piece.Arg]))
		} else {
			fields = append(fields, fmt.Sprintf("Lit: %s", strconv.Quote(piece.Lit)))
		}
		parts = append(parts, "{"+strings.Join(fields, ", ")+"}")
	}
	return "{" + strings.Join(parts, ", ") + "}"
}

func helperName(selector string) string {
	open := strings.IndexByte(selector, '(')
	if open <= 0 {
		return ""
	}
	name := strings.TrimPrefix(selector[:open], "return ")
	if _, ok := pluralHelpers[name]; ok {
		return name
	}
	return ""
}

// goSymbol turns a resolved ID into an exported Go identifier. A hyphen and a
// dot are both separators, because an ID is catalog policy and is not required
// to be spellable in Go.
func goSymbol(id string) string {
	var out strings.Builder
	upper := true
	for _, r := range id {
		switch {
		case r == '.' || r == '-' || r == '_':
			upper = true
		case upper:
			out.WriteRune(unicode.ToUpper(r))
			upper = false
		default:
			out.WriteRune(r)
		}
	}
	return out.String()
}

// localeConst names the exported constant for a locale tag, so a caller writes
// messages.JA rather than looking one up by string.
func localeConst(tag string) string {
	var out strings.Builder
	for _, r := range tag {
		if r == '-' || r == '_' {
			continue
		}
		out.WriteRune(unicode.ToUpper(r))
	}
	return out.String()
}
