// Code generated by tinybind; DO NOT EDIT.

//go:build fasthttp

package fastfixture

import (
	"io"
	"net/http"

	httpbind "github.com/shibukawa/tinybind-go/fasthttpbind"
	"github.com/shibukawa/tinybind-go/jsonbind"
	"github.com/shibukawa/tinygodriver/fasthttp"
)

func init() {
	httpbind.RegisterBind[Greeting](bindGreeting)
	httpbind.RegisterWrite[Greeted](writeGreeted)
}

func decodeGreetingBytes(data []byte) (Greeting, error) {
	if jsonbind.IsBlank(data) {
		var out Greeting
		return out, nil
	}
	var p jsonbind.Parser
	p.Reset(data)
	out, err := decodeGreetingJSON(&p)
	if err != nil {
		return out, err
	}
	if err := p.End(); err != nil {
		return out, err
	}
	return out, nil
}

func decodeGreetingJSON(p *jsonbind.Parser) (Greeting, error) {
	var out Greeting
	null, err := p.ObjectStart()
	if err != nil || null {
		return out, err
	}
	for n := 0; ; n++ {
		key, ok, err := p.ObjectKey(n)
		if err != nil {
			return out, err
		}
		if !ok {
			return out, nil
		}
		switch string(key) {
		case "name":
			v, err := p.String()
			if err != nil {
				return out, jsonbind.FieldError("name", "invalid string", err)
			}
			out.Name = v
		default:
			if err := p.SkipValue(); err != nil {
				return out, err
			}
		}
	}
}

func bindGreeting(r *fasthttp.RequestCtx) (Greeting, error) {
	var out Greeting
	var presentName bool
	queryVals := httpbind.Queries(r)
	needName := true
	if qv, ok := httpbind.QueryLookup(queryVals, "name"); ok {
		needName = false
		presentName = true
		out.Name = qv
	}
	if needName {
		if httpbind.IsJSONRequest(r) {
			data, err := httpbind.ReadJSONBody(r)
			if err != nil {
				return out, err
			}
			if !jsonbind.IsBlank(data) {
				var bodyParser jsonbind.Parser
				bodyParser.Reset(data)
				p := &bodyParser
				null, err := p.ObjectStart()
				if err != nil {
					return out, httpbind.JSONBodyError(err)
				}
				if null {
					return out, httpbind.JSONBodyNotObject()
				}
				for n := 0; ; n++ {
					key, ok, err := p.ObjectKey(n)
					if err != nil {
						return out, httpbind.JSONBodyError(err)
					}
					if !ok {
						break
					}
					switch string(key) {
					case "name":
						if !needName {
							if err := p.SkipValue(); err != nil {
								return out, httpbind.JSONBodyError(err)
							}
							continue
						}
						presentName = true
						v, err := p.String()
						if err != nil {
							return out, jsonbind.FieldError("name", "invalid string", err)
						}
						out.Name = v
					default:
						if err := p.SkipValue(); err != nil {
							return out, httpbind.JSONBodyError(err)
						}
					}
				}
				if err := p.End(); err != nil {
					return out, httpbind.JSONBodyError(err)
				}
			}
		} else {
			formBody, _, err := httpbind.ReadFormBody(r, true, false)
			if err != nil {
				return out, err
			}
			if needName && formBody != nil {
				if fv, ok := formBody["name"]; ok {
					presentName = true
					out.Name = fv
				}
			}
		}
	}
	var checkFields []httpbind.FieldError
	if !presentName || out.Name == "" {
		checkFields = append(checkFields, httpbind.Field("name", "input", "required"))
	}
	if len(checkFields) > 0 {
		return out, httpbind.Validation(checkFields...)
	}
	return out, nil
}

func appendGreetedJSON(dst []byte, v Greeted) []byte {
	dst = append(dst, '{')
	dst = append(dst, "\"message\":"...)
	dst = jsonbind.AppendString(dst, v.Message)
	return append(dst, '}')
}

func encodeGreeted(w io.Writer, v Greeted) error {
	buf := jsonbind.GetBuffer()
	*buf = appendGreetedJSON((*buf)[:0], v)
	*buf = append(*buf, '\n')
	_, err := w.Write(*buf)
	jsonbind.PutBuffer(buf)
	return err
}

func writeGreeted(r *fasthttp.RequestCtx, v Greeted) error {
	buf := jsonbind.GetBuffer()
	*buf = appendGreetedJSON((*buf)[:0], v)
	err := httpbind.WriteJSONBytes(r, http.StatusOK, *buf)
	jsonbind.PutBuffer(buf)
	return err
}
