// Code generated by tinybind; DO NOT EDIT.

//go:build fasthttp

package fastfixture

import pwfast "github.com/shibukawa/popcornwave/pwfast"

// RegisterRoutes installs every route this package declares.
//
// The patterns are the ones the net/http source registers, unchanged where
// the two routers spell a parameter the same way.
func RegisterRoutes(r pwfast.RouteInstaller) {
	r.Handle("GET", "/greet", Greet)
}
