// Code generated by tinybind; DO NOT EDIT.

//go:build fasthttp

package fastfixture

import (
	pw "github.com/shibukawa/popcornwave/pwfast"
	"github.com/shibukawa/tinygodriver/fasthttp"
)

// Greet is the authored handler, and the only one written here. Its fasthttp
// counterpart is generated from it.
func Greet(ctx *fasthttp.RequestCtx) {
	ask, err := pw.Parse[Greeting](ctx)
	if err != nil {
		pw.WriteProblem(ctx, err)
		return
	}
	pw.WriteAPI(ctx, Greeted{Message: "hello, " + ask.Name})
}
