//go:build !tinybind_no_openapi

// Code generated by tinybind; DO NOT EDIT.

package fastfixture

import "github.com/shibukawa/tinybind-go"

func init() {
	httpbind.RegisterOpenAPIFragmentString("github.com/shibukawa/popcornwave/internal/fastfixture", openapiFragmentJSON)
}

const openapiFragmentJSON = "{\"components\":{\"schemas\":{\"ProblemDetails\":{\"properties\":{\"code\":{\"type\":\"string\"},\"detail\":{\"type\":\"string\"},\"errors\":{\"items\":{\"properties\":{\"field\":{\"type\":\"string\"},\"location\":{\"type\":\"string\"},\"message\":{\"type\":\"string\"}},\"type\":\"object\"},\"type\":\"array\"},\"status\":{\"type\":\"integer\"},\"title\":{\"type\":\"string\"},\"type\":{\"type\":\"string\"}},\"type\":\"object\"}}},\"paths\":{}}"
