// Code generated by Popcorn Wave via TinyBind; DO NOT EDIT.

package pages

import (
	"github.com/shibukawa/popcornwave/internal/pagesfixture/pages/users/id_"
	"github.com/shibukawa/popcornwave/pw"
	"github.com/shibukawa/popcornwave/pwpage"
	"github.com/shibukawa/popcornwave/pwruntime"
	"net/http"
)

// Register installs every discovered route on mux.
//
// Options are passed to the runtime on each render, so a caller supplies its
// per-request cache, timeout, and error hook here.
func Register(mux pwpage.Router, options ...pwpage.Option) {
	mux.HandleFunc("GET /{$}",
		func(w http.ResponseWriter, r *http.Request) {
			route, err := DecodeRoute(r)
			if err != nil {
				pw.WriteProblem(w, r, err)
				return
			}
			_ = route
			params := PageParams{}
			wrappers := []pwpage.Wrapper{
				BindLayout(LayoutParams{}),
			}
			if err := pwpage.Render(w, r, wrappers, Page(params), options...); err != nil {
				pw.WriteProblem(w, r, err)
			}
		})
	mux.HandleFunc("GET /users/{id}",
		func(w http.ResponseWriter, r *http.Request) {
			route, err := id_.DecodeRoute(r)
			if err != nil {
				pw.WriteProblem(w, r, err)
				return
			}
			_ = route
			params := id_.PageParams{
				Id:   route.ID,
				Page: route.Page,
			}
			wrappers := []pwpage.Wrapper{
				BindLayout(LayoutParams{}),
			}
			if err := pwpage.Render(w, r, wrappers, id_.Page(params), options...); err != nil {
				pw.WriteProblem(w, r, err)
			}
		})
	mux.HandleFunc("POST /users/{id}",
		func(w http.ResponseWriter, r *http.Request) {
			switch pw.ActionSelector(r, "_action") {
			case "d71506d06c1e/Retire":
				pw.DispatchAction(w, r, id_.Retire)
			default:
				pw.WriteProblem(w, r, pw.BadRequest(pw.Problem{Code: "unknown_action", Message: "no server function on this page matches the submitted selector"}))
			}
		})

	mux.HandleFunc("POST /_action/00369cf962b6/Rename", id_.Rename)
	mux.HandleFunc("POST /_action/d71506d06c1e/Retire", id_.Retire)
	mux.HandleFunc("POST /_action/d0775f011114/profile", id_.ActionProfile)
}

// Routes lists what the filesystem knows about each route, so a
// framework can build a sitemap or an inspector without a metadata format.
//
// Pattern is spelled for the router these routes are registered on, while Path
// is the address the filesystem declared. They differ only where the router
// spells a segment differently than net/http does.
var Routes = []RouteInfo{
	{Pattern: "GET /{$}", Path: "/", Dir: "", Params: nil},
	{Pattern: "GET /users/{id}", Path: "/users/{id}", Dir: "users/id_", Params: []string{"id"}},
}

// RouteInfo is one entry of Routes.
type RouteInfo struct {
	// Pattern is what the route is registered under, spelled for the router.
	Pattern string
	// Path is the address the filesystem declared, in net/http spelling. It is
	// the one to build a sitemap from, because a router's own spelling of a
	// catch-all is not a URL.
	Path string
	// Dir is the route directory relative to the route root.
	Dir string
	// Params names the dynamic segments, in route order.
	Params []string
}

// Actions lists every server function endpoint. Every exported
// handler in a route package is reachable whether or not a template references
// it, so this is what makes that surface inspectable.
//
// An endpoint grants nothing: the path hides structure but is not a capability
// token, so each handler still authenticates and authorizes its own caller.
var Actions = []ActionInfo{
	{Pattern: "POST /_action/00369cf962b6/Rename", Path: "/_action/00369cf962b6/Rename", Dir: "users/id_", Handler: "Rename", Hash: "00369cf962b6", Published: "rename", Typed: false},
	{Pattern: "POST /_action/d71506d06c1e/Retire", Path: "/_action/d71506d06c1e/Retire", Dir: "users/id_", Handler: "Retire", Hash: "d71506d06c1e", Published: "retire", Typed: false},
	{Pattern: "POST /_action/d0775f011114/profile", Path: "/_action/d0775f011114/profile", Dir: "users/id_", Handler: "profile", Hash: "d0775f011114", Published: "profile", Typed: true},
}

// ActionInfo is one entry of Actions.
type ActionInfo struct {
	// Pattern is the stdlib ServeMux pattern the endpoint is registered under.
	Pattern string
	// Path is the pattern without its method.
	Path string
	// Dir is the declaring package's directory relative to the route root.
	Dir string
	// Handler is the exported Go function name.
	Handler string
	// Hash is the stable half of the path.
	Hash string
	// Published is the identifier client script calls this action through, and
	// Typed reports that a declaration admitted it rather than its signature.
	// A typed action is reached only by a call; no template can name one.
	Published string
	Typed     bool
}

func init() {
	pwruntime.RegisterPageActions("GET /users/{id}",
		pwruntime.PageAction{Name: "rename", Path: "/_action/00369cf962b6/Rename"},
		pwruntime.PageAction{Name: "retire", Path: "/_action/d71506d06c1e/Retire"},
		pwruntime.PageAction{Name: "profile", Path: "/_action/d0775f011114/profile"},
	)
}
