// How the three pw/* replies are rendered. Each one has a not-ok state, and
// how that state reads is the whole point: an empty editor or an empty tree
// with no explanation is what these views exist to avoid.

import assert from "node:assert/strict";
import { createRequire } from "node:module";
import { test } from "node:test";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const require = createRequire(import.meta.url);
const here = dirname(fileURLToPath(import.meta.url));
const { GENERATED_SCHEME, renderGenerated, routeItems, routePlaceholder, routeCaveat } = require(
  join(here, "..", "src", "views.js"),
);

test("a generated fragment is shown with the file it came from", async () => {
  const rendered = renderGenerated({
    status: "ok",
    declaration: "Card",
    file: "templates/card_pw_gen.go",
    text: "func Card(w io.Writer) error {\n\treturn nil\n}",
    stale: false,
  });

  assert.match(rendered, /templates\/card_pw_gen\.go/);
  assert.match(rendered, /func Card/);
  assert.match(rendered, /read-only/);
});

test("a stale fragment says so rather than passing itself off as current", async () => {
  const rendered = renderGenerated({
    status: "ok",
    declaration: "Card",
    file: "templates/card_pw_gen.go",
    text: "func Card() {}",
    stale: true,
  });

  assert.match(rendered, /source has changed/);
  assert.match(rendered, /pw generate/);
});

test("nothing generated is a document with a reason, not an empty one", async () => {
  // policy:editor-tool-execution keeps generation behind an explicit action,
  // so the view has to say what to run rather than quietly generating.
  const rendered = renderGenerated({
    status: "absent",
    declaration: "Card",
    message: "pw generate has not run for this directory",
  });

  assert.match(rendered, /No generated code to show for Card/);
  assert.match(rendered, /pw generate has not run/);
  assert.match(rendered, /Nothing is generated by opening/);
});

test("the scheme is the extension's own, so nothing writes through it", async () => {
  assert.equal(GENERATED_SCHEME, "popcornweb-generated");
});

test("a route carries its page, its tree, and its layout chain", async () => {
  const [route] = routeItems({
    routes: [
      {
        path: "/rooms/id_",
        page: "pages/rooms/id_/page.pw.html",
        pageUri: "file:///w/pages/rooms/id_/page.pw.html",
        layouts: ["pages/layout.pw.html"],
        handler: "pages/rooms/id_/page.go",
        root: "pages",
      },
    ],
  });

  assert.equal(route.path, "/rooms/id_");
  assert.match(route.description, /page\.go/);
  assert.match(route.tooltip, /layouts: pages\/layout\.pw\.html/);
});

test("a route with no handler says the handler is generated", async () => {
  // Which rung of concept:page-tree a route sits on is the thing a reader is
  // scanning the tree for.
  const [route] = routeItems({
    routes: [{ path: "/", page: "pages/page.pw.html", pageUri: "file:///w/p", root: "pages" }],
  });

  assert.match(route.tooltip, /handler: generated/);
  assert.equal(route.description, "pages");
});

test("no routes is a different statement from no server", async () => {
  assert.match(routePlaceholder(null), /not running/);
  assert.match(routePlaceholder({ routes: [] }), /register its routes in Go/);
  assert.equal(routePlaceholder({ routes: [{ path: "/" }] }), "");
});

test("what the view does not cover is carried out of the reply", async () => {
  // A view that silently covers half the URL space reads as if it covered all
  // of it, which is the failure decision:dual-router-coexistence makes easy.
  assert.match(routeCaveat({ notCovered: "registered routes, which are calls in Go" }), /registered routes/);
  assert.equal(routeCaveat({}), "");
});
