// Command runtimegen produces the browser runtime embedded by package pw.
package main

import (
	"bytes"
	"fmt"
	"os"

	"github.com/evanw/esbuild/pkg/api"
)

func main() {
	parts := make([][]byte, 0, 3)
	for _, name := range []string{"boundary.js", "update.js", "updateboot.js"} {
		source, err := os.ReadFile(name)
		if err != nil {
			fatal(err)
		}
		parts = append(parts, source)
	}
	result := api.Transform(string(bytes.Join(parts, []byte("\n"))), api.TransformOptions{
		Loader:            api.LoaderJS,
		Target:            api.ES2020,
		MinifyIdentifiers: true,
		MinifySyntax:      true,
		MinifyWhitespace:  true,
		LegalComments:     api.LegalCommentsNone,
	})
	if len(result.Errors) != 0 {
		for _, message := range result.Errors {
			fmt.Fprintln(os.Stderr, message.Text)
		}
		os.Exit(1)
	}
	output := append([]byte("// Code generated by internal/runtimegen; DO NOT EDIT.\n"), result.Code...)
	if err := os.WriteFile("runtime.min.js", output, 0o644); err != nil {
		fatal(err)
	}
}

func fatal(err error) {
	fmt.Fprintln(os.Stderr, err)
	os.Exit(1)
}
