package pwcli

import (
	"bytes"
	"encoding/json"
	"fmt"
	"go/parser"
	"go/token"
	"net/http"
	"os"
	"path/filepath"
	"strconv"
)

// assetManifestFile is the generated registration the application links. It is
// Go rather than a data file the runtime parses: the table is known at build
// time, and a startup parse would cost every process what one build already
// knows, including a TinyGo target that has no reason to carry a decoder.
const assetManifestFile = "public_manifest_pw_gen.go"

// assetManifestJSON is the same data for tooling. Nothing reads it at runtime;
// it exists so pw doctor and a developer can see what the build decided.
const assetManifestJSON = "dist/manifest.json"

type manifestRepresentationJSON struct {
	Path            string `json:"path"`
	MediaType       string `json:"media_type"`
	ContentEncoding string `json:"content_encoding,omitempty"`
	Length          int    `json:"length"`
	ETag            string `json:"etag"`
	Preference      int    `json:"preference,omitempty"`
	// External names bytes read from the second authored tree at request time.
	// Length and ETag stay zero for one of these, because that tree is deployed
	// as its own artifact and a validator taken here could outlive its bytes.
	External bool `json:"external,omitempty"`
}

type manifestEntryJSON struct {
	URL             string                       `json:"url"`
	CacheControl    string                       `json:"cache_control"`
	Representations []manifestRepresentationJSON `json:"representations"`
}

// writeAssetManifest emits both forms from one grouping, so the table the
// application links and the file a person reads can never disagree.
func writeAssetManifest(root string, assets []derivedAsset) error {
	grouped := groupByURL(assets)
	packageName, err := publicPackageName(root)
	if err != nil {
		return err
	}
	source, err := renderAssetManifest(packageName, grouped)
	if err != nil {
		return err
	}
	if err := writeScaffoldFile(filepath.Join(root, assetManifestFile), source); err != nil {
		return fmt.Errorf("public assets: write %s: %w", assetManifestFile, err)
	}
	encoded, err := json.MarshalIndent(grouped, "", "  ")
	if err != nil {
		return err
	}
	target := filepath.Join(root, filepath.FromSlash(assetManifestJSON))
	if err := os.MkdirAll(filepath.Dir(target), 0o755); err != nil {
		return err
	}
	return writeScaffoldFile(target, append(encoded, '\n'))
}

// groupByURL folds every representation of one URL into one entry. The order is
// the walk's, which is sorted, so two builds of the same tree emit the same
// bytes.
func groupByURL(assets []derivedAsset) []manifestEntryJSON {
	var entries []manifestEntryJSON
	index := map[string]int{}
	for _, asset := range assets {
		position, found := index[asset.url]
		if !found {
			entries = append(entries, manifestEntryJSON{URL: asset.url, CacheControl: cacheControlFor(asset)})
			position = len(entries) - 1
			index[asset.url] = position
		}
		entries[position].Representations = append(entries[position].Representations, manifestRepresentationJSON{
			Path:            asset.path,
			MediaType:       asset.mediaType,
			ContentEncoding: asset.encoding,
			Length:          asset.length,
			ETag:            asset.etag,
			Preference:      asset.preference,
			External:        asset.external,
		})
	}
	return entries
}

// The two cache policies, one per kind of name.
const (
	// derivedCacheControl revalidates. A file that kept the name its author
	// wrote can serve different bytes after a rebuild, so the strong validator
	// does the work and an unchanged asset costs a 304 with no body.
	derivedCacheControl = "public, no-cache"
	// immutableCacheControl is only honest for a name carrying the digest of
	// its own bytes: different bytes are a different URL, so the response can
	// promise never to change and be believed.
	immutableCacheControl = "public, max-age=31536000, immutable"
)

func cacheControlFor(asset derivedAsset) string {
	if asset.immutable {
		return immutableCacheControl
	}
	return derivedCacheControl
}

func renderAssetManifest(packageName string, entries []manifestEntryJSON) ([]byte, error) {
	var out bytes.Buffer
	fmt.Fprintf(&out, "// Code generated by pw build. DO NOT EDIT.\n\npackage %s\n\n", packageName)
	out.WriteString("import \"github.com/shibukawa/popcornwave/middlewares\"\n\n")
	out.WriteString("// The build knows every URL, every representation, and every validator, so\n")
	out.WriteString("// the request path reads bytes and computes nothing.\n")
	out.WriteString("func init() {\n\tmiddlewares.RegisterPublicManifest([]middlewares.AssetEntry{\n")
	for _, entry := range entries {
		fmt.Fprintf(&out, "\t\t{URL: %s, CacheControl: %s, Representations: []middlewares.AssetRepresentation{\n",
			strconv.Quote(entry.URL), strconv.Quote(entry.CacheControl))
		for _, representation := range entry.Representations {
			fmt.Fprintf(&out, "\t\t\t{Path: %s, MediaType: %s, ContentEncoding: %s, Length: %d, ETag: %s, Preference: %d, External: %t},\n",
				strconv.Quote(representation.Path), strconv.Quote(representation.MediaType),
				strconv.Quote(representation.ContentEncoding), representation.Length,
				strconv.Quote(representation.ETag), representation.Preference, representation.External)
		}
		out.WriteString("\t\t}},\n")
	}
	out.WriteString("\t})\n}\n")
	return out.Bytes(), nil
}

// publicPackageName reads the package the scaffolded embed lives in, so the
// generated registration compiles beside it whatever the project named it.
func publicPackageName(root string) (string, error) {
	name := filepath.Join(root, "public.go")
	file, err := parser.ParseFile(token.NewFileSet(), name, nil, parser.PackageClauseOnly)
	if err != nil {
		return "", fmt.Errorf("public assets: read package clause of public.go: %w", err)
	}
	return file.Name.Name, nil
}

func detectContentType(content []byte) string {
	return http.DetectContentType(content)
}
