package pwcli

import (
	"context"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// The asset build clears the served tree and fills it from public/, so the
// stylesheet has to exist by then. Written afterwards it is a file the run never
// serves: what got copied is whatever public/generated/app.css held before, and
// on a project's first run that is the scaffolded placeholder — a page arriving
// with a stylesheet that defines nothing it uses.
//
// This pins the order both pw build and pw dev depend on. It exercises the two
// builds rather than either command, so a command that reorders them again is
// caught by the symptom being reproducible here, not by this test failing.
func TestTheServedTreeCarriesTheBuiltStylesheet(t *testing.T) {
	root := derivedFixture(t)
	for _, directory := range []string{filepath.Join("public", "generated"), "assets"} {
		if err := os.MkdirAll(filepath.Join(root, directory), 0o755); err != nil {
			t.Fatal(err)
		}
	}
	// What pw init leaves behind, and what the served tree must not keep.
	writeTestFile(t, filepath.Join(root, "public", "generated", "app.css"), "/* Generated by Tailwind CSS. */\n")
	writeTestFile(t, filepath.Join(root, "assets", "app.css"), "@import \"tailwindcss\";\n")
	stubTailwindBinary(t, root, ".built { color: red }\n")

	config := tailwindConfig{
		Enabled: true,
		Input:   "assets/app.css",
		Output:  "public/generated/app.css",
	}
	if err := buildTailwind(context.Background(), root, config, &strings.Builder{}, &strings.Builder{}); err != nil {
		t.Fatal(err)
	}
	if _, err := buildDerivedAssets(root, assetsConfig{}); err != nil {
		t.Fatal(err)
	}

	served, err := os.ReadFile(filepath.Join(root, filepath.FromSlash(derivedPublicDir), "generated", "app.css"))
	if err != nil {
		t.Fatalf("the served tree has no stylesheet: %v", err)
	}
	if !strings.Contains(string(served), ".built") {
		t.Errorf("the served stylesheet is not the built one:\n%s", served)
	}
}

// stubTailwindBinary puts a tailwindcss on PATH that writes body to whatever -o
// names, which is all this needs from it.
func stubTailwindBinary(t *testing.T, root, body string) {
	t.Helper()
	bin := filepath.Join(root, "bin")
	if err := os.Mkdir(bin, 0o755); err != nil {
		t.Fatal(err)
	}
	tool := filepath.Join(bin, "tailwindcss")
	writeTestFile(t, tool, `#!/bin/sh
output=""
while [ $# -gt 0 ]; do
  case "$1" in
    -o) output="$2"; shift 2 ;;
    *) shift ;;
  esac
done
printf '`+body+`' > "$output"
`)
	if err := os.Chmod(tool, 0o755); err != nil {
		t.Fatal(err)
	}
	t.Setenv("PATH", bin+string(os.PathListSeparator)+os.Getenv("PATH"))
}
