package pwcli

import (
	"bytes"
	"context"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"io"
	"io/fs"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/shibukawa/popcornwave/internal/pwgen"
	"github.com/shibukawa/tinybind-go/generator"
	"golang.org/x/mod/modfile"
)

func runGenerate(ctx context.Context, args []string, stdout io.Writer) error {
	check := false
	for _, arg := range args {
		switch arg {
		case "--check":
			check = true
		default:
			return fmt.Errorf("generate: unknown argument %q", arg)
		}
	}
	root, err := projectRoot(".")
	if err != nil {
		return err
	}
	config, err := loadProjectConfig(root)
	if err != nil {
		return err
	}
	directories, err := packageDirectories(root)
	if err != nil {
		return err
	}
	options, err := pwgen.Options()
	if err != nil {
		return err
	}
	runner := generator.New(options)
	var changes []fileChange
	for _, directory := range directories {
		planned, err := planDirectory(ctx, runner, directory)
		if err != nil {
			return err
		}
		changes = append(changes, planned...)
	}
	changes, err = planBootstrapLink(root, config.Main, changes)
	if err != nil {
		return err
	}
	sort.Slice(changes, func(i, j int) bool { return changes[i].path < changes[j].path })
	if check && len(changes) > 0 {
		drift := changePaths(changes)
		return fmt.Errorf("generated files are stale:\n  %s", strings.Join(drift, "\n  "))
	}
	if err := applyFileChanges(changes); err != nil {
		return err
	}
	for _, path := range changePaths(changes) {
		fmt.Fprintln(stdout, path)
	}
	return nil
}

func planBootstrapLink(root, mainPath string, changes []fileChange) ([]fileChange, error) {
	var documents []string
	err := filepath.WalkDir(root, func(path string, entry fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if entry.IsDir() {
			switch entry.Name() {
			case ".git", "vendor", "node_modules", ".devbox":
				return filepath.SkipDir
			}
			return nil
		}
		if entry.Name() == "document.pw.html" {
			documents = append(documents, path)
		}
		return nil
	})
	if err != nil {
		return nil, err
	}
	if len(documents) > 1 {
		return nil, fmt.Errorf("multiple default documents: %s", strings.Join(documents, ", "))
	}
	mainDirectory := filepath.Clean(filepath.Join(root, filepath.FromSlash(mainPath)))
	target := filepath.Join(mainDirectory, "popcornwave_bootstrap_pw_gen.go")
	filtered := changes[:0]
	for _, change := range changes {
		if change.path != target {
			filtered = append(filtered, change)
		}
	}
	hasPublic := false
	if info, err := os.Stat(filepath.Join(root, "public.go")); err == nil {
		hasPublic = !info.IsDir()
	} else if !os.IsNotExist(err) {
		return nil, err
	}
	if len(documents) == 0 && !hasPublic {
		if _, err := os.Stat(target); err == nil {
			filtered = append(filtered, fileChange{path: target, remove: true})
		} else if !os.IsNotExist(err) {
			return nil, err
		}
		return filtered, nil
	}
	moduleSource, err := os.ReadFile(filepath.Join(root, "go.mod"))
	if err != nil {
		return nil, err
	}
	modulePath := modfile.ModulePath(moduleSource)
	if modulePath == "" {
		return nil, fmt.Errorf("go.mod does not declare a module path")
	}
	var imports []string
	if len(documents) == 1 {
		relativeDocumentDir, err := filepath.Rel(root, filepath.Dir(documents[0]))
		if err != nil {
			return nil, err
		}
		documentImport := modulePath
		if relativeDocumentDir != "." {
			documentImport += "/" + filepath.ToSlash(relativeDocumentDir)
		}
		imports = append(imports, documentImport)
	}
	if hasPublic && mainDirectory != filepath.Clean(root) {
		imports = append(imports, modulePath)
	}
	sort.Strings(imports)
	imports = slicesCompact(imports)
	if len(imports) == 0 {
		if _, err := os.Stat(target); err == nil {
			filtered = append(filtered, fileChange{path: target, remove: true})
		} else if !os.IsNotExist(err) {
			return nil, err
		}
		return filtered, nil
	}
	packageName, err := goPackageName(mainDirectory)
	if err != nil {
		return nil, err
	}
	var generated strings.Builder
	fmt.Fprintf(&generated, `// Code generated by Popcorn Wave; DO NOT EDIT.

package %s

import (
`, packageName)
	for _, path := range imports {
		fmt.Fprintf(&generated, "\t_ %q\n", path)
	}
	generated.WriteString(")\n")
	source, err := format.Source([]byte(generated.String()))
	if err != nil {
		return nil, err
	}
	current, readErr := os.ReadFile(target)
	if readErr == nil && bytes.Equal(current, source) {
		return filtered, nil
	}
	if readErr != nil && !os.IsNotExist(readErr) {
		return nil, readErr
	}
	return append(filtered, fileChange{path: target, source: source}), nil
}

func slicesCompact(values []string) []string {
	if len(values) < 2 {
		return values
	}
	out := values[:1]
	for _, value := range values[1:] {
		if value != out[len(out)-1] {
			out = append(out, value)
		}
	}
	return out
}

func goPackageName(directory string) (string, error) {
	entries, err := os.ReadDir(directory)
	if err != nil {
		return "", err
	}
	for _, entry := range entries {
		if entry.IsDir() || !strings.HasSuffix(entry.Name(), ".go") ||
			strings.HasSuffix(entry.Name(), "_test.go") ||
			strings.HasSuffix(entry.Name(), "_pw_gen.go") {
			continue
		}
		path := filepath.Join(directory, entry.Name())
		file, err := parser.ParseFile(token.NewFileSet(), path, nil, parser.PackageClauseOnly)
		if err != nil {
			return "", err
		}
		return file.Name.Name, nil
	}
	return "", fmt.Errorf("no handwritten Go source in main package %s", directory)
}

func packageDirectories(root string) ([]string, error) {
	found := map[string]bool{}
	err := filepath.WalkDir(root, func(path string, entry fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if entry.IsDir() {
			switch entry.Name() {
			case ".git", "vendor", "node_modules", ".devbox":
				return filepath.SkipDir
			}
			return nil
		}
		name := entry.Name()
		if (strings.HasSuffix(name, ".go") && !strings.HasSuffix(name, "_test.go")) ||
			strings.HasSuffix(name, ".pw.html") || strings.HasSuffix(name, ".pw.sql") {
			found[filepath.Dir(path)] = true
		}
		return nil
	})
	if err != nil {
		return nil, err
	}
	out := make([]string, 0, len(found))
	for directory := range found {
		out = append(out, directory)
	}
	sort.Strings(out)
	return out, nil
}

type fileChange struct {
	path   string
	source []byte
	remove bool
}

func planDirectory(ctx context.Context, runner *generator.Generator, directory string) ([]fileChange, error) {
	openAPI, err := hasGoSources(directory)
	if err != nil {
		return nil, err
	}
	artifacts, err := runner.GenerateArtifacts(ctx, generator.GenerateRequest{
		Dir:               directory,
		OpenAPI:           openAPI,
		SQLContextOnlyAPI: true,
	})
	if err != nil {
		return nil, fmt.Errorf("%s: %w", directory, err)
	}

	grouped := make(map[string][]generator.Artifact)
	for _, artifact := range artifacts {
		target := filepath.Join(directory, artifact.OutputBase+"_pw_gen.go")
		grouped[target] = append(grouped[target], artifact)
		if artifact.Kind == generator.ArtifactHTMLTemplate &&
			filepath.Base(artifact.SourcePath) == "document.pw.html" {
			grouped[target] = append(grouped[target], documentRegistrationArtifact(artifact.PackageName))
		}
	}
	expected := make(map[string]bool, len(grouped))
	var changes []fileChange
	for target, group := range grouped {
		expected[target] = true
		source, err := mergeArtifacts(group)
		if err != nil {
			return nil, err
		}
		current, readErr := os.ReadFile(target)
		if readErr == nil && bytes.Equal(current, source) {
			continue
		}
		if readErr != nil && !os.IsNotExist(readErr) {
			return nil, readErr
		}
		changes = append(changes, fileChange{path: target, source: source})
	}
	entries, err := os.ReadDir(directory)
	if err != nil {
		return nil, err
	}
	for _, entry := range entries {
		if entry.IsDir() || !strings.HasSuffix(entry.Name(), "_pw_gen.go") {
			continue
		}
		path := filepath.Join(directory, entry.Name())
		if !expected[path] {
			changes = append(changes, fileChange{path: path, remove: true})
		}
	}
	return changes, nil
}

func documentRegistrationArtifact(packageName string) generator.Artifact {
	return generator.Artifact{
		Kind:        generator.ArtifactHTMLTemplate,
		OutputBase:  "document",
		PackageName: packageName,
		GoSource: []byte("package " + packageName + `

import "github.com/shibukawa/popcornwave/pw"

func init() {
	pw.RegisterHTMLDocument(BindDocument(DocumentParams{}))
}
`),
	}
}

func hasGoSources(directory string) (bool, error) {
	entries, err := os.ReadDir(directory)
	if err != nil {
		return false, err
	}
	for _, entry := range entries {
		name := entry.Name()
		if !entry.IsDir() && strings.HasSuffix(name, ".go") && !strings.HasSuffix(name, "_test.go") &&
			!strings.HasSuffix(name, "_pw_gen.go") {
			return true, nil
		}
	}
	return false, nil
}

func mergeArtifacts(artifacts []generator.Artifact) ([]byte, error) {
	if len(artifacts) == 0 {
		return nil, fmt.Errorf("popcornwave: no artifacts to merge")
	}
	if len(artifacts) == 1 {
		return artifacts[0].GoSource, nil
	}
	packageName := artifacts[0].PackageName
	fset := token.NewFileSet()
	imports := make(map[string]*ast.ImportSpec)
	var declarations []ast.Decl
	for index, artifact := range artifacts {
		if artifact.PackageName != packageName {
			return nil, fmt.Errorf("popcornwave: artifact package mismatch %q and %q", packageName, artifact.PackageName)
		}
		file, err := parser.ParseFile(fset, fmt.Sprintf("artifact-%d.go", index), artifact.GoSource, parser.ParseComments)
		if err != nil {
			return nil, fmt.Errorf("parse %s artifact: %w", artifact.Kind, err)
		}
		for _, item := range file.Imports {
			alias := ""
			if item.Name != nil {
				alias = item.Name.Name
			}
			spec := &ast.ImportSpec{
				Path: &ast.BasicLit{Kind: token.STRING, Value: item.Path.Value},
			}
			if alias != "" {
				spec.Name = ast.NewIdent(alias)
			}
			imports[alias+"\x00"+item.Path.Value] = spec
		}
		for _, declaration := range file.Decls {
			if generated, ok := declaration.(*ast.GenDecl); ok && generated.Tok == token.IMPORT {
				continue
			}
			declarations = append(declarations, declaration)
		}
	}
	keys := make([]string, 0, len(imports))
	for key := range imports {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	if len(keys) > 0 {
		specs := make([]ast.Spec, 0, len(keys))
		for _, key := range keys {
			specs = append(specs, imports[key])
		}
		declarations = append([]ast.Decl{&ast.GenDecl{Tok: token.IMPORT, Specs: specs}}, declarations...)
	}
	file := &ast.File{Name: ast.NewIdent(packageName), Decls: declarations}
	var output bytes.Buffer
	output.WriteString("// Code generated by Popcorn Wave via TinyBind; DO NOT EDIT.\n\n")
	if err := format.Node(&output, fset, file); err != nil {
		return nil, err
	}
	output.WriteByte('\n')
	source, err := format.Source(output.Bytes())
	if err != nil {
		return nil, err
	}
	return source, nil
}

func changePaths(changes []fileChange) []string {
	paths := make([]string, 0, len(changes))
	for _, change := range changes {
		relative, err := filepath.Rel(".", change.path)
		if err != nil || relative == "" {
			relative = change.path
		}
		paths = append(paths, relative)
	}
	sort.Strings(paths)
	return paths
}

func applyFileChanges(changes []fileChange) error {
	type stagedFile struct {
		target string
		temp   string
	}
	var staged []stagedFile
	cleanup := func() {
		for _, file := range staged {
			_ = os.Remove(file.temp)
		}
	}
	for _, change := range changes {
		if change.remove {
			continue
		}
		file, err := os.CreateTemp(filepath.Dir(change.path), "."+filepath.Base(change.path)+".*")
		if err != nil {
			cleanup()
			return err
		}
		temp := file.Name()
		staged = append(staged, stagedFile{target: change.path, temp: temp})
		if err := file.Chmod(0o644); err != nil {
			_ = file.Close()
			cleanup()
			return err
		}
		if _, err := file.Write(change.source); err != nil {
			_ = file.Close()
			cleanup()
			return err
		}
		if err := file.Sync(); err != nil {
			_ = file.Close()
			cleanup()
			return err
		}
		if err := file.Close(); err != nil {
			cleanup()
			return err
		}
	}
	for _, file := range staged {
		if err := os.Rename(file.temp, file.target); err != nil {
			cleanup()
			return err
		}
	}
	for _, change := range changes {
		if change.remove {
			if err := os.Remove(change.path); err != nil && !os.IsNotExist(err) {
				return err
			}
		}
	}
	return nil
}
