package pwcli

import (
	"bytes"
	"context"
	"errors"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"io"
	"io/fs"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/shibukawa/popcornwave/internal/pwgen"
	"github.com/shibukawa/tinybind-go/generator"
	"golang.org/x/mod/modfile"
)

const generateUsage = "usage: pw generate [--check]"

func runGenerate(ctx context.Context, args []string, stdout io.Writer) error {
	check := false
	for _, arg := range args {
		switch arg {
		case "--check":
			check = true
		default:
			return fmt.Errorf("generate: unknown argument %q; %s", arg, generateUsage)
		}
	}
	root, err := projectRoot(".")
	if err != nil {
		return err
	}
	config, err := loadProjectConfig(root)
	if err != nil {
		return err
	}
	directories, err := packageDirectories(root, config.Generate)
	if err != nil {
		return err
	}
	if err := reportSourcesOutsideScope(root, config, stdout); err != nil {
		return err
	}
	// The page trees are generated first because their output is planned as part
	// of the directory it lands in, and a tree root may hold no source the walk
	// above would have found.
	pageArtifacts, err := planPageTrees(root, config)
	if err != nil {
		return err
	}
	directories, err = withPageDirectories(directories, pageArtifacts)
	if err != nil {
		return err
	}
	options, err := pwgen.Options(engineFor(config.Database).SQLDialect)
	if err != nil {
		return err
	}
	runner := generator.New(options)
	var changes []fileChange
	for _, directory := range directories {
		planned, err := planDirectory(ctx, runner, directory, directoryPurposes(root, config.Generate, directory), pageArtifacts[directory])
		if err != nil {
			return err
		}
		changes = append(changes, planned...)
	}
	changes, err = planBootstrapLink(root, config, changes)
	if err != nil {
		return err
	}
	sort.Slice(changes, func(i, j int) bool { return changes[i].path < changes[j].path })
	if check && len(changes) > 0 {
		drift := changePaths(root, changes)
		return fmt.Errorf("generated files are stale:\n  %s", strings.Join(drift, "\n  "))
	}
	if err := applyFileChanges(changes); err != nil {
		return err
	}
	for _, path := range changePaths(root, changes) {
		fmt.Fprintln(stdout, path)
	}
	return nil
}

func planBootstrapLink(root string, config projectConfig, changes []fileChange) ([]fileChange, error) {
	var documents []string
	err := walkSources(root, config.Generate.Templates, func(path string, entry fs.DirEntry) error {
		if entry.Name() == "document.pw.html" {
			documents = append(documents, path)
		}
		return nil
	})
	if err != nil {
		return nil, err
	}
	if len(documents) > 1 {
		return nil, fmt.Errorf("multiple default documents: %s", strings.Join(documents, ", "))
	}
	mainDirectory := filepath.Clean(filepath.Join(root, filepath.FromSlash(config.Main)))
	target := filepath.Join(mainDirectory, "popcornwave_bootstrap_pw_gen.go")
	filtered := changes[:0]
	for _, change := range changes {
		if change.path != target {
			filtered = append(filtered, change)
		}
	}
	hasPublic := false
	if info, err := os.Stat(filepath.Join(root, "public.go")); err == nil {
		hasPublic = !info.IsDir()
	} else if !os.IsNotExist(err) {
		return nil, err
	}
	if len(documents) == 0 && !hasPublic {
		if _, err := os.Stat(target); err == nil {
			filtered = append(filtered, fileChange{path: target, remove: true})
		} else if !os.IsNotExist(err) {
			return nil, err
		}
		return filtered, nil
	}
	moduleSource, err := os.ReadFile(filepath.Join(root, "go.mod"))
	if err != nil {
		return nil, err
	}
	modulePath := modfile.ModulePath(moduleSource)
	if modulePath == "" {
		return nil, fmt.Errorf("go.mod does not declare a module path")
	}
	var imports []string
	if len(documents) == 1 {
		relativeDocumentDir, err := filepath.Rel(root, filepath.Dir(documents[0]))
		if err != nil {
			return nil, err
		}
		documentImport := modulePath
		if relativeDocumentDir != "." {
			documentImport += "/" + filepath.ToSlash(relativeDocumentDir)
		}
		imports = append(imports, documentImport)
	}
	if hasPublic && mainDirectory != filepath.Clean(root) {
		imports = append(imports, modulePath)
	}
	sort.Strings(imports)
	imports = slicesCompact(imports)
	if len(imports) == 0 {
		if _, err := os.Stat(target); err == nil {
			filtered = append(filtered, fileChange{path: target, remove: true})
		} else if !os.IsNotExist(err) {
			return nil, err
		}
		return filtered, nil
	}
	packageName, err := goPackageName(mainDirectory)
	if err != nil {
		return nil, err
	}
	var generated strings.Builder
	fmt.Fprintf(&generated, `// Code generated by Popcorn Wave; DO NOT EDIT.

package %s

import (
`, packageName)
	for _, path := range imports {
		fmt.Fprintf(&generated, "\t_ %q\n", path)
	}
	generated.WriteString(")\n")
	source, err := format.Source([]byte(generated.String()))
	if err != nil {
		return nil, err
	}
	current, readErr := os.ReadFile(target)
	if readErr == nil && bytes.Equal(current, source) {
		return filtered, nil
	}
	if readErr != nil && !os.IsNotExist(readErr) {
		return nil, readErr
	}
	return append(filtered, fileChange{path: target, source: source}), nil
}

func slicesCompact(values []string) []string {
	if len(values) < 2 {
		return values
	}
	out := values[:1]
	for _, value := range values[1:] {
		if value != out[len(out)-1] {
			out = append(out, value)
		}
	}
	return out
}

func goPackageName(directory string) (string, error) {
	entries, err := os.ReadDir(directory)
	if err != nil {
		return "", err
	}
	for _, entry := range entries {
		if entry.IsDir() || !strings.HasSuffix(entry.Name(), ".go") ||
			strings.HasSuffix(entry.Name(), "_test.go") ||
			strings.HasSuffix(entry.Name(), "_pw_gen.go") {
			continue
		}
		path := filepath.Join(directory, entry.Name())
		file, err := parser.ParseFile(token.NewFileSet(), path, nil, parser.PackageClauseOnly)
		if err != nil {
			return "", err
		}
		return file.Name.Name, nil
	}
	return "", fmt.Errorf("no handwritten Go source in main package %s", directory)
}

// walkSources visits every file under the configured source directories. The
// generator reads nothing else in the project, so where generated code comes
// from is the popcornwave.toml list and not the shape of the directory tree.
func walkSources(root string, sources []string, visit func(path string, entry fs.DirEntry) error) error {
	for _, source := range sources {
		directory := filepath.Join(root, filepath.FromSlash(source))
		err := filepath.WalkDir(directory, func(path string, entry fs.DirEntry, err error) error {
			if err != nil {
				return err
			}
			if entry.IsDir() {
				switch entry.Name() {
				case ".git", "vendor", "node_modules", ".devbox":
					return filepath.SkipDir
				}
				return nil
			}
			return visit(path, entry)
		})
		if err != nil {
			return err
		}
	}
	return nil
}

// generationInput reports whether a file name is something the generator reads.
func generationInput(name string) bool {
	return (strings.HasSuffix(name, ".go") && !strings.HasSuffix(name, "_test.go")) ||
		strings.HasSuffix(name, ".pw.html") || strings.HasSuffix(name, ".pw.sql")
}

// directoryPurposes reports which generation purposes list a directory. A
// directory usually serves more than one, because a page template lives beside
// the handler that renders it.
//
// root and directory must be spelled the same way, which in practice means both
// absolute: a directory that resolves to no purpose is one whose generated files
// are swept as stale.
func directoryPurposes(root string, scope generationScope, directory string) generationPurposes {
	within := func(sources []string) bool {
		for _, source := range sources {
			if pathWithin(filepath.Join(root, filepath.FromSlash(source)), directory) {
				return true
			}
		}
		return false
	}
	return generationPurposes{
		handlers:  within(scope.Handlers),
		templates: within(scope.Templates),
		queries:   within(scope.Queries),
		config:    within(scope.Config),
		pages:     within(scope.Pages),
	}
}

// generationPurposes is the set of purposes one directory belongs to.
type generationPurposes struct {
	handlers  bool
	templates bool
	queries   bool
	config    bool
	// pages marks a directory inside a page tree root. Its templates are
	// compiled by the tree run rather than the flat one, so what this enables
	// here is the request binding a server action needs.
	pages bool
}

// any reports whether the directory serves any purpose at all.
func (p generationPurposes) any() bool {
	return p.handlers || p.templates || p.queries || p.config || p.pages
}

// keeps maps an artifact back to the purpose that may produce it. Go analysis
// runs for the whole directory, so binding and configuration artifacts are
// selected here rather than at discovery.
func (p generationPurposes) keeps(kind generator.ArtifactKind) bool {
	switch kind {
	case generator.ArtifactBinding:
		// A page tree gets binders so a server action can read a typed request,
		// but no OpenAPI: a rendered page is not a published contract, and an
		// action endpoint is one page's implementation detail.
		return p.handlers || p.pages
	case generator.ArtifactOpenAPI:
		return p.handlers
	case generator.ArtifactHTMLTemplate:
		return p.templates
	case generator.ArtifactSQLTemplate:
		return p.queries
	case generator.ArtifactConfigBind:
		return p.config
	default:
		return false
	}
}

func packageDirectories(root string, scope generationScope) ([]string, error) {
	found := map[string]bool{}
	for _, sources := range [][]string{scope.Handlers, scope.Templates, scope.Queries, scope.Config, scope.Pages} {
		err := walkSources(root, sources, func(path string, entry fs.DirEntry) error {
			if generationInput(entry.Name()) {
				found[filepath.Dir(path)] = true
			}
			return nil
		})
		if err != nil {
			return nil, err
		}
	}
	out := make([]string, 0, len(found))
	for directory := range found {
		out = append(out, directory)
	}
	sort.Strings(out)
	return out, nil
}

// strayReport is one source the purpose that owns its kind does not list.
type strayReport struct {
	path    string
	message string
}

// reportSourcesOutsideScope warns about framework sources their own purpose
// leaves out. They are reported rather than generated from, because a project
// may keep samples or fixtures beside its code on purpose; a Go file is never
// reported, since ordinary Go code lives throughout a project and a call site
// outside its purpose simply has no generated binding.
func reportSourcesOutsideScope(root string, config projectConfig, stdout io.Writer) error {
	bootstrap := filepath.Join(
		filepath.Clean(filepath.Join(root, filepath.FromSlash(config.Main))),
		"popcornwave_bootstrap_pw_gen.go",
	)
	var stray []strayReport
	err := filepath.WalkDir(root, func(path string, entry fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if entry.IsDir() {
			switch entry.Name() {
			case ".git", "vendor", "node_modules", ".devbox":
				return filepath.SkipDir
			}
			return nil
		}
		if path == bootstrap {
			return nil
		}
		name := entry.Name()
		purposes := directoryPurposes(root, config.Generate, filepath.Dir(path))
		relative, relErr := filepath.Rel(root, path)
		if relErr != nil {
			relative = path
		}
		relative = filepath.ToSlash(relative)
		switch {
		case purposes.pages && strings.HasSuffix(name, ".pw.html"):
			// The tree run compiles the names a page tree reserves. Any other
			// template inside a root is compiled by neither run.
			if !reservedPageTemplates[name] {
				stray = append(stray, strayReport{relative, fmt.Sprintf(
					"pw: %s is inside a page tree but is not %s, %s, or %s, so nothing compiles it",
					relative, pwgen.PageFile, pwgen.LayoutFile, pwgen.DocumentFile)})
			}
		case strings.HasSuffix(name, ".pw.html") && !purposes.templates:
			stray = append(stray, strayReport{relative, fmt.Sprintf(
				"pw: %s is outside generate.templates and is not generated from; list its directory to include it", relative)})
		case strings.HasSuffix(name, ".pw.sql") && !purposes.queries:
			stray = append(stray, strayReport{relative, fmt.Sprintf(
				"pw: %s is outside generate.queries and is not generated from; list its directory to include it", relative)})
		case strings.HasSuffix(name, "_pw_gen.go") && !purposes.any():
			stray = append(stray, strayReport{relative, fmt.Sprintf(
				"pw: %s was generated outside every generate purpose and is now stale; delete it or list its directory", relative)})
		}
		return nil
	})
	if err != nil {
		return err
	}
	sort.Slice(stray, func(i, j int) bool { return stray[i].path < stray[j].path })
	for _, report := range stray {
		fmt.Fprintln(stdout, report.message)
	}
	return nil
}

type fileChange struct {
	path   string
	source []byte
	remove bool
}

// disabledTemplatePattern matches no file, and switches off one template kind
// for a directory the purpose that owns it does not list. Discovery is skipped
// rather than filtered afterwards, so an unlisted template is never parsed.
const disabledTemplatePattern = "*.not-a-generation-source"

// planDirectory plans every generated file of one directory. extra carries the
// artifacts another run produced for it, which today means the compiled
// components, decoder, and registry of a page tree: they are planned here so
// one directory has one staleness sweep, and so a component and a binder that
// derive the same base name merge into one file rather than deleting each
// other.
func planDirectory(ctx context.Context, runner *generator.Generator, directory string, purposes generationPurposes, extra []generator.Artifact) ([]fileChange, error) {
	goSources, err := hasGoSources(directory)
	if err != nil {
		return nil, err
	}
	request := generator.GenerateRequest{
		Dir:                 directory,
		OpenAPI:             goSources && purposes.handlers,
		SQLContextOnlyAPI:   true,
		HTMLTemplatePattern: disabledTemplatePattern,
		SQLTemplatePattern:  disabledTemplatePattern,
	}
	if purposes.templates {
		request.HTMLTemplatePattern = ""
	}
	if purposes.queries {
		request.SQLTemplatePattern = ""
	}
	artifacts, err := runner.GenerateArtifacts(ctx, request)
	if err != nil && !errors.Is(err, generator.ErrNothingToGenerate) {
		// A page tree route package usually holds no request model at all, so
		// finding nothing is the ordinary outcome rather than a failure.
		return nil, fmt.Errorf("%s: %w", directory, err)
	}

	grouped := make(map[string][]generator.Artifact)
	for _, artifact := range extra {
		target := filepath.Join(directory, artifact.OutputBase+"_pw_gen.go")
		grouped[target] = append(grouped[target], artifact)
	}
	for _, artifact := range artifacts {
		if !purposes.keeps(artifact.Kind) {
			continue
		}
		target := filepath.Join(directory, artifact.OutputBase+"_pw_gen.go")
		grouped[target] = append(grouped[target], artifact)
		if artifact.Kind == generator.ArtifactHTMLTemplate &&
			filepath.Base(artifact.SourcePath) == "document.pw.html" {
			grouped[target] = append(grouped[target], documentRegistrationArtifact(artifact.PackageName))
		}
	}
	expected := make(map[string]bool, len(grouped))
	var changes []fileChange
	for target, group := range grouped {
		expected[target] = true
		source, err := mergeArtifacts(group)
		if err != nil {
			return nil, err
		}
		current, readErr := os.ReadFile(target)
		if readErr == nil && bytes.Equal(current, source) {
			continue
		}
		if readErr != nil && !os.IsNotExist(readErr) {
			return nil, readErr
		}
		changes = append(changes, fileChange{path: target, source: source})
	}
	entries, err := os.ReadDir(directory)
	if err != nil {
		return nil, err
	}
	for _, entry := range entries {
		if entry.IsDir() || !strings.HasSuffix(entry.Name(), "_pw_gen.go") {
			continue
		}
		path := filepath.Join(directory, entry.Name())
		if !expected[path] {
			changes = append(changes, fileChange{path: path, remove: true})
		}
	}
	return changes, nil
}

func documentRegistrationArtifact(packageName string) generator.Artifact {
	return generator.Artifact{
		Kind:        generator.ArtifactHTMLTemplate,
		OutputBase:  "document",
		PackageName: packageName,
		GoSource: []byte("package " + packageName + `

import "github.com/shibukawa/popcornwave/pw"

func init() {
	pw.RegisterHTMLDocument(BindDocument(DocumentParams{}))
}
`),
	}
}

func hasGoSources(directory string) (bool, error) {
	entries, err := os.ReadDir(directory)
	if err != nil {
		return false, err
	}
	for _, entry := range entries {
		name := entry.Name()
		if !entry.IsDir() && strings.HasSuffix(name, ".go") && !strings.HasSuffix(name, "_test.go") &&
			!strings.HasSuffix(name, "_pw_gen.go") {
			return true, nil
		}
	}
	return false, nil
}

func mergeArtifacts(artifacts []generator.Artifact) ([]byte, error) {
	if len(artifacts) == 0 {
		return nil, fmt.Errorf("popcornwave: no artifacts to merge")
	}
	if len(artifacts) == 1 {
		return artifacts[0].GoSource, nil
	}
	packageName := artifacts[0].PackageName
	fset := token.NewFileSet()
	imports := make(map[string]*ast.ImportSpec)
	var declarations []ast.Decl
	for index, artifact := range artifacts {
		if artifact.PackageName != packageName {
			return nil, fmt.Errorf("popcornwave: artifact package mismatch %q and %q", packageName, artifact.PackageName)
		}
		file, err := parser.ParseFile(fset, fmt.Sprintf("artifact-%d.go", index), artifact.GoSource, parser.ParseComments)
		if err != nil {
			return nil, fmt.Errorf("parse %s artifact: %w", artifact.Kind, err)
		}
		for _, item := range file.Imports {
			alias := ""
			if item.Name != nil {
				alias = item.Name.Name
			}
			spec := &ast.ImportSpec{
				Path: &ast.BasicLit{Kind: token.STRING, Value: item.Path.Value},
			}
			if alias != "" {
				spec.Name = ast.NewIdent(alias)
			}
			imports[alias+"\x00"+item.Path.Value] = spec
		}
		for _, declaration := range file.Decls {
			if generated, ok := declaration.(*ast.GenDecl); ok && generated.Tok == token.IMPORT {
				continue
			}
			declarations = append(declarations, declaration)
		}
	}
	keys := make([]string, 0, len(imports))
	for key := range imports {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	if len(keys) > 0 {
		specs := make([]ast.Spec, 0, len(keys))
		for _, key := range keys {
			specs = append(specs, imports[key])
		}
		declarations = append([]ast.Decl{&ast.GenDecl{Tok: token.IMPORT, Specs: specs}}, declarations...)
	}
	file := &ast.File{Name: ast.NewIdent(packageName), Decls: declarations}
	var output bytes.Buffer
	output.WriteString("// Code generated by Popcorn Wave via TinyBind; DO NOT EDIT.\n\n")
	if err := format.Node(&output, fset, file); err != nil {
		return nil, err
	}
	output.WriteByte('\n')
	source, err := format.Source(output.Bytes())
	if err != nil {
		return nil, err
	}
	return source, nil
}

// changePaths renders the touched files for the operator. A generated path is
// absolute because the walk started from the project root, and printing it that
// way buries the interesting part of the line; the operator is standing in the
// project, so the prefix they are already in comes off.
func changePaths(root string, changes []fileChange) []string {
	prefixes := []string{}
	if working, err := os.Getwd(); err == nil {
		prefixes = append(prefixes, working+string(filepath.Separator))
	}
	// The working directory may be below the root, in which case a file
	// elsewhere in the project still shortens against the root.
	prefixes = append(prefixes, root+string(filepath.Separator))
	paths := make([]string, 0, len(changes))
	for _, change := range changes {
		paths = append(paths, shortenPath(change.path, prefixes))
	}
	sort.Strings(paths)
	return paths
}

// shortenPath cuts the first matching prefix. A path under none of them is left
// absolute, because a shortened form would name a file the operator cannot find
// from where they are.
func shortenPath(path string, prefixes []string) string {
	for _, prefix := range prefixes {
		if shortened, ok := strings.CutPrefix(path, prefix); ok {
			return shortened
		}
	}
	return path
}

func applyFileChanges(changes []fileChange) error {
	type stagedFile struct {
		target string
		temp   string
	}
	var staged []stagedFile
	cleanup := func() {
		for _, file := range staged {
			_ = os.Remove(file.temp)
		}
	}
	for _, change := range changes {
		if change.remove {
			continue
		}
		file, err := os.CreateTemp(filepath.Dir(change.path), "."+filepath.Base(change.path)+".*")
		if err != nil {
			cleanup()
			return err
		}
		temp := file.Name()
		staged = append(staged, stagedFile{target: change.path, temp: temp})
		if err := file.Chmod(0o644); err != nil {
			_ = file.Close()
			cleanup()
			return err
		}
		if _, err := file.Write(change.source); err != nil {
			_ = file.Close()
			cleanup()
			return err
		}
		if err := file.Sync(); err != nil {
			_ = file.Close()
			cleanup()
			return err
		}
		if err := file.Close(); err != nil {
			cleanup()
			return err
		}
	}
	for _, file := range staged {
		if err := os.Rename(file.temp, file.target); err != nil {
			cleanup()
			return err
		}
	}
	for _, change := range changes {
		if change.remove {
			if err := os.Remove(change.path); err != nil && !os.IsNotExist(err) {
				return err
			}
		}
	}
	return nil
}
