package pwcli

import (
	"context"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// writePageTreeFixture creates a project whose only router is a page tree: a
// root page under a layout, and a dynamic route with a typed Load beside it.
func writePageTreeFixture(t *testing.T) string {
	t.Helper()
	root := t.TempDir()
	for _, directory := range []string{
		filepath.Join("cmd", "fixture"),
		filepath.Join("pages", "users", "id_"),
	} {
		if err := os.MkdirAll(filepath.Join(root, directory), 0o755); err != nil {
			t.Fatal(err)
		}
	}
	writeTestFile(t, filepath.Join(root, "go.mod"), "module example.test/fixture\n\ngo 1.26.0\n")
	writeTestFile(t, filepath.Join(root, "popcornwave.toml"),
		"[project]\nname = \"fixture\"\nmain = \"./cmd/fixture\"\n\n[generate]\n"+
			"handlers = []\ntemplates = []\nqueries = []\nconfig = []\npages = [\"pages\"]\n")
	writeTestFile(t, filepath.Join(root, "cmd", "fixture", "main.go"), "package main\n\nfunc main() {}\n")

	writeTestFile(t, filepath.Join(root, "pages", "layout.pw.html"), `package pages

export component Layout(children: html): html {
<main>{children}</main>
}
`)
	writeTestFile(t, filepath.Join(root, "pages", "page.pw.html"), `package pages

export component Page(): html {
<h1>home</h1>
}
`)
	writeTestFile(t, filepath.Join(root, "pages", "users", "id_", "page.pw.html"), `package id_

external LoadName(id: string): string

export component Page(id: string): html {
{val name = LoadName(id)}
<h1>{name}</h1>
}
`)
	writeTestFile(t, filepath.Join(root, "pages", "users", "id_", "page.go"), `package id_

func LoadName(id string) (string, error) { return id, nil }
`)
	return root
}

func generateIn(t *testing.T, root string, args ...string) string {
	t.Helper()
	previous, err := os.Getwd()
	if err != nil {
		t.Fatal(err)
	}
	if err := os.Chdir(root); err != nil {
		t.Fatal(err)
	}
	defer os.Chdir(previous)

	var output strings.Builder
	if err := runGenerate(context.Background(), args, &output); err != nil {
		t.Fatalf("generate %v: %v\n%s", args, err, output.String())
	}
	return output.String()
}

// A directory holding a page template is a route, and generation writes the
// registration nobody had to.
func TestRunGenerateWritesPageTree(t *testing.T) {
	root := writePageTreeFixture(t)
	generateIn(t, root)

	for _, relative := range []string{
		filepath.Join("pages", "page_pw_gen.go"),
		filepath.Join("pages", "layout_pw_gen.go"),
		filepath.Join("pages", "route_pw_gen.go"),
		filepath.Join("pages", "routes_pw_gen.go"),
		filepath.Join("pages", "users", "id_", "page_pw_gen.go"),
		filepath.Join("pages", "users", "id_", "route_pw_gen.go"),
	} {
		if _, err := os.Stat(filepath.Join(root, relative)); err != nil {
			t.Errorf("page tree file missing: %v", err)
		}
	}

	registry := readTestFile(t, filepath.Join(root, "pages", "routes_pw_gen.go"))
	for _, want := range []string{
		`mux.HandleFunc("GET /{$}"`,
		`mux.HandleFunc("GET /users/{id}"`,
		"func Register(mux pwpage.Router",
		"pwpage.Render(w, r,",
		"pw.WriteProblem(w, r, err)",
		"Code generated by Popcorn Wave",
	} {
		if !strings.Contains(registry, want) {
			t.Errorf("registry does not contain %q:\n%s", want, registry)
		}
	}
	// The registry is the one file a generated tree must not offer a
	// constructor for: an interface is not something generated code can build.
	if strings.Contains(registry, "func NewServeMux") {
		t.Errorf("registry emitted a constructor for an interface:\n%s", registry)
	}
	// A page renders through the framework response path, never the bare
	// template runtime, which is what keeps the document shell and the error
	// pages in play.
	if strings.Contains(registry, "htmlbind.") {
		t.Errorf("registry calls the template runtime directly:\n%s", registry)
	}
}

// A page's own loader is called by the compiled component rather than by the
// registry, because the template is what names it and binds its result. The
// registry carries the route's inputs to the component, and nothing else.
func TestRunGeneratePageTreeCallsItsLoader(t *testing.T) {
	root := writePageTreeFixture(t)
	generateIn(t, root)

	component := readTestFile(t, filepath.Join(root, "pages", "users", "id_", "page_pw_gen.go"))
	if !strings.Contains(component, "LoadName(") {
		t.Errorf("the bound loader is not called by the component:\n%s", component)
	}
	registry := readTestFile(t, filepath.Join(root, "pages", "routes_pw_gen.go"))
	if strings.Contains(registry, "LoadName(") {
		t.Errorf("the registry calls the loader, which is the retired shape:\n%s", registry)
	}
	decoder := readTestFile(t, filepath.Join(root, "pages", "users", "id_", "route_pw_gen.go"))
	// Through the framework accessor rather than off the request value. That
	// read is one no second transport can follow — fasthttp has no path routing
	// of its own, so there is no method on its request to call — and routing
	// both through pw is what lets one decoder template serve either.
	//
	// The spelling is asserted because a regression to r.PathValue compiles and
	// passes everything except a fasthttp build, which nobody runs by default.
	if !strings.Contains(decoder, `pw.PathValue(r, "id")`) {
		t.Errorf("decoder does not read the dynamic segment:\n%s", decoder)
	}
	if strings.Contains(decoder, `r.PathValue(`) && !strings.Contains(decoder, `pw.PathValue(r,`) {
		t.Errorf("decoder reads the path off the request directly:\n%s", decoder)
	}
}

// Regenerating an unchanged tree writes nothing, which is what makes --check
// meaningful and what proves the emitted bytes are deterministic.
func TestRunGeneratePageTreeIsStable(t *testing.T) {
	root := writePageTreeFixture(t)
	generateIn(t, root)
	first := readTestFile(t, filepath.Join(root, "pages", "routes_pw_gen.go"))

	second := generateIn(t, root)
	if strings.Contains(second, "routes_pw_gen.go") {
		t.Errorf("unchanged tree was rewritten:\n%s", second)
	}
	if readTestFile(t, filepath.Join(root, "pages", "routes_pw_gen.go")) != first {
		t.Error("regeneration changed the registry of an unchanged tree")
	}
}

// The shape a scaffolded project has on its first day: a page tree, and a main
// that mounts it by calling the Register this generation is about to write. The
// tree holds templates and no Go at all until then, so a run that analyses the
// main first loads a package that does not exist and stops — having written
// nothing, which leaves the next run the same tree and the same failure. This
// is the first pw dev of a new project, not some later clean checkout.
func TestRunGenerateWritesAPageTreeBeforeTheMainThatImportsIt(t *testing.T) {
	root := writePageTreeFixture(t)
	writeTestFile(t, filepath.Join(root, "popcornwave.toml"),
		"[project]\nname = \"fixture\"\nmain = \"./cmd/fixture\"\n\n[generate]\n"+
			"handlers = []\ntemplates = []\nqueries = []\nconfig = [\"cmd/fixture\"]\npages = [\"pages\"]\n")
	writeTestFile(t, filepath.Join(root, "cmd", "fixture", "main.go"), `package main

import "example.test/fixture/pages"

func main() { _ = pages.Routes }
`)
	generateIn(t, root)

	if _, err := os.Stat(filepath.Join(root, "pages", "routes_pw_gen.go")); err != nil {
		t.Fatalf("the page package the main imports was never written: %v", err)
	}
}

// A page tree root is not a handler directory, so no page route reaches the
// OpenAPI document. The registrations are in the generated registry, and
// discovery is told to skip what this command wrote.
func TestRunGeneratePageTreeWritesNoOpenAPI(t *testing.T) {
	root := writePageTreeFixture(t)
	generateIn(t, root)

	err := filepath.Walk(root, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}
		if info.IsDir() || !strings.HasSuffix(path, "_pw_gen.go") {
			return nil
		}
		if strings.Contains(readTestFile(t, path), "AssembleOpenAPI") ||
			strings.Contains(readTestFile(t, path), "RegisterOpenAPI") {
			t.Errorf("%s carries an OpenAPI fragment", path)
		}
		return nil
	})
	if err != nil {
		t.Fatal(err)
	}
}

// A template inside a tree under a name the tree reserves nothing for is
// compiled by neither run, so it is named rather than silently ignored.
func TestRunGenerateReportsUnreservedPageTemplate(t *testing.T) {
	root := writePageTreeFixture(t)
	writeTestFile(t, filepath.Join(root, "pages", "partial.pw.html"), `package pages

export component Partial(): html {
<span>x</span>
}
`)
	output := generateIn(t, root)
	if !strings.Contains(output, "pages/partial.pw.html is inside a page tree") {
		t.Errorf("unreserved template was not reported:\n%s", output)
	}
}

func readTestFile(t *testing.T, path string) string {
	t.Helper()
	source, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	return string(source)
}

// A page route is a directory, so the developer loop has to notice one that did
// not exist when it started. It does, because the walk compares files rather
// than subscribing to events, and a route always carries the template that
// makes it one: the new file is the change.
func TestWatchSnapshotSeesANewPageRoute(t *testing.T) {
	root := writePageTreeFixture(t)
	before, err := snapshotWatchFiles(root, nil)
	if err != nil {
		t.Fatal(err)
	}
	if err := os.MkdirAll(filepath.Join(root, "pages", "about"), 0o755); err != nil {
		t.Fatal(err)
	}
	writeTestFile(t, filepath.Join(root, "pages", "about", "page.pw.html"), `package about

export component Page(): html {
<h1>about</h1>
}
`)
	after, err := snapshotWatchFiles(root, nil)
	if err != nil {
		t.Fatal(err)
	}
	if equalWatchState(before, after) {
		t.Error("a new page route did not change the watch state")
	}

	// Removing the directory removes the route with it, which the same
	// comparison reports for the same reason.
	if err := os.RemoveAll(filepath.Join(root, "pages", "about")); err != nil {
		t.Fatal(err)
	}
	restored, err := snapshotWatchFiles(root, nil)
	if err != nil {
		t.Fatal(err)
	}
	if !equalWatchState(before, restored) {
		t.Error("removing a page route left the watch state changed")
	}
}

// writeRenamedTreeFixture is the same project with both routers under names the
// scaffold would not have chosen, which is what the purpose lists are for.
func writeRenamedTreeFixture(t *testing.T) string {
	t.Helper()
	root := t.TempDir()
	for _, directory := range []string{
		filepath.Join("cmd", "fixture"),
		filepath.Join("site", "docs", "slug_"),
		"api",
	} {
		if err := os.MkdirAll(filepath.Join(root, directory), 0o755); err != nil {
			t.Fatal(err)
		}
	}
	writeTestFile(t, filepath.Join(root, "go.mod"), "module example.test/fixture\n\ngo 1.26.0\n")
	writeTestFile(t, filepath.Join(root, "popcornwave.toml"),
		"[project]\nname = \"fixture\"\nmain = \"./cmd/fixture\"\n\n[generate]\n"+
			"handlers = [\"api\"]\ntemplates = [\"api\"]\nqueries = []\nconfig = []\npages = [\"site\"]\n")
	writeTestFile(t, filepath.Join(root, "cmd", "fixture", "main.go"), "package main\n\nfunc main() {}\n")
	writeTestFile(t, filepath.Join(root, "api", "index.go"),
		"package api\n\nimport \"net/http\"\n\nvar mux = http.NewServeMux()\n\nfunc Handlers() *http.ServeMux { return mux }\n")
	writeTestFile(t, filepath.Join(root, "site", "layout.pw.html"), `package site

export component Layout(children: html): html {
<main>{children}</main>
}
`)
	writeTestFile(t, filepath.Join(root, "site", "docs", "slug_", "page.pw.html"), `package slug_

export component Page(slug: string): html {
<h1>{slug}</h1>
}
`)
	return root
}

// Nothing downstream of popcornwave.toml knows the names handlers and pages:
// those are what the scaffold writes, and the purpose lists are what everything
// reads. A project that renamed both keeps working.
func TestGenerationFollowsRenamedDirectories(t *testing.T) {
	root := writeRenamedTreeFixture(t)
	generateIn(t, root)

	for _, relative := range []string{
		filepath.Join("site", "routes_pw_gen.go"),
		filepath.Join("site", "layout_pw_gen.go"),
		filepath.Join("site", "docs", "slug_", "page_pw_gen.go"),
		filepath.Join("site", "docs", "slug_", "route_pw_gen.go"),
	} {
		if _, err := os.Stat(filepath.Join(root, relative)); err != nil {
			t.Errorf("the renamed tree did not generate: %v", err)
		}
	}
	// The import path of a route package follows the directory, so a renamed
	// tree cannot keep importing the old one.
	registry := readTestFile(t, filepath.Join(root, "site", "routes_pw_gen.go"))
	for _, want := range []string{
		"package site",
		`example.test/fixture/site/docs/slug_`,
		`mux.HandleFunc("GET /docs/{slug}"`,
	} {
		if !strings.Contains(registry, want) {
			t.Errorf("registry does not contain %q:\n%s", want, registry)
		}
	}
	if _, err := os.Stat(filepath.Join(root, "pages")); !os.IsNotExist(err) {
		t.Error("generation created the default directory in a project that renamed it")
	}
}

// pw new offers the destinations the project configured, not the ones the
// scaffold would have created.
func TestNewPageOffersTheConfiguredTree(t *testing.T) {
	root := writeRenamedTreeFixture(t)
	writeTestFile(t, filepath.Join(root, "config.dev.toml"), "[server]\naddr = \":8080\"\n")
	state, err := loadProjectState(root)
	if err != nil {
		t.Fatal(err)
	}
	destinations := pageDestinations(state)
	if len(destinations) != 1 || destinations[0] != "site" {
		t.Fatalf("page destinations = %v", destinations)
	}
	plan, err := planPage(state, newOptions{
		Kind: newKindPage, Package: destinations[0], Path: "/about", Rung: pageRungTemplate,
	})
	if err != nil {
		t.Fatal(err)
	}
	if _, wrote := plan.creates["site/about/page.pw.html"]; !wrote {
		t.Errorf("the page was not planned inside the configured tree: %v", plan.creates)
	}
}
