package pwcli

import (
	"errors"
	"fmt"
	"strings"

	"github.com/shibukawa/tinybind-go/generator"
)

// The second transport's half of a project is generated by system:tinybind from
// the same run as the first one's: the derived handlers, and the binders and
// writers that serve them over the fasthttp request value. Setting
// Options.Transform is the whole of asking for it.
//
// Two things about that are this framework's rather than the generator's, and
// they are what this file holds. Refusals are relayed with one sentence upstream
// cannot say, and the route registration the generator also offers is declined,
// because a page tree here installs on pwfastpage.Router rather than on the
// router that emitter names.

// transportRefusal turns a generation failure into what a reader can act on,
// when what failed was the derivation.
//
// Adoption is all-or-nothing, so one refusal stops the run: there is no adapter
// for a handler to fall back to, and generating the rest would leave a package
// that silently serves fewer routes.
//
// The upstream text is relayed rather than reworded, per rule:transport-handle-checks,
// with one addition it cannot make: a refusal naming a pw call is this
// framework's missing call pattern rather than the application's mistake, and
// saying so is the difference between a developer editing their handler for an
// hour and reporting a framework bug in a minute.
func transportRefusal(directory string, err error) error {
	var refusals generator.TransformRefusals
	if !errors.As(err, &refusals) || len(refusals) == 0 {
		return fmt.Errorf("%s: %w", directory, err)
	}
	message := "the fasthttp build cannot be derived from " + directory + ":\n" + refusals.Error()
	if names := frameworkRefusals(refusals); len(names) > 0 {
		message += "\n" + strings.Join(names, "\n") +
			"\nThose name framework entries with no registered call pattern, which is a defect in " +
			"Popcorn Wave rather than in this application: no edit to a handler can supply one. " +
			"Please report it.\n"
	}
	return errors.New(message)
}

// frameworkRefusals picks out the refusals caused by a pw call.
//
// It reads the rendered detail rather than the call graph, because the detail is
// what upstream publishes about a refusal and re-deriving the callee here would
// be a second opinion to keep in agreement. The detail names the callee by its
// package name and function, so "pw." is the whole test.
func frameworkRefusals(refusals generator.TransformRefusals) []string {
	var out []string
	for _, refusal := range refusals {
		if refusal.Kind != generator.RefusalUnknownCall || !strings.Contains(refusal.Detail, " to pw.") {
			continue
		}
		out = append(out, "  "+refusal.Position.String()+"  "+refusal.Detail)
	}
	return out
}
