[project]
name = "live_render"
main = "./cmd/live_render"

[generate]
handlers = ["handlers"]
templates = ["handlers", "templates"]
queries = []
config = ["cmd/live_render"]

[dev.watch]
includes = []
excludes = []

[assets.tailwind]
enabled = true
input = "assets/app.css"
output = "public/generated/app.css"
minify = true
