package pwmigrate

import (
	"context"
	"database/sql"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"strings"

	"github.com/shibukawa/popcornweb/internal/sqlscript"
)

// sequenceTable holds AUTOINCREMENT counters and cannot be recreated by an
// ordinary CREATE TABLE statement.
const sequenceTable = "sqlite_sequence"

// Snapshot applies every migration to a throwaway database and returns SQL that
// reproduces the result, including recorded migration versions.
func Snapshot(ctx context.Context, sources fs.FS) (string, error) {
	directory, err := os.MkdirTemp("", "pwmigrate-snapshot-")
	if err != nil {
		return "", fmt.Errorf("snapshot workspace: %w", err)
	}
	defer os.RemoveAll(directory)
	target, err := Open("sqlite://" + filepath.Join(directory, "snapshot.db"))
	if err != nil {
		return "", err
	}
	defer target.Close()
	if _, err := Apply(ctx, target, sources, ActionUp, 0); err != nil {
		return "", err
	}
	return Dump(ctx, target.DB)
}

// Dump writes deterministic SQL that reproduces a SQLite database.
func Dump(ctx context.Context, db *sql.DB) (string, error) {
	objects, err := schemaObjects(ctx, db)
	if err != nil {
		return "", err
	}
	var builder strings.Builder
	builder.WriteString("-- generated by pw migrate snapshot; do not edit\n")
	for _, object := range objects {
		if object.kind != "table" {
			continue
		}
		builder.WriteString(object.sql)
		builder.WriteString(";\n")
	}
	for _, object := range objects {
		if object.kind != "table" {
			continue
		}
		rows, err := tableRows(ctx, db, object.name)
		if err != nil {
			return "", err
		}
		for _, row := range rows {
			fmt.Fprintf(&builder, "INSERT INTO %s VALUES(%s);\n", quoteIdentifier(object.name), row)
		}
	}
	sequences, err := sequenceRows(ctx, db)
	if err != nil {
		return "", err
	}
	if sequences != nil {
		builder.WriteString("PRAGMA writable_schema=ON;\n")
		builder.WriteString("CREATE TABLE IF NOT EXISTS sqlite_sequence(name,seq);\n")
		builder.WriteString("DELETE FROM sqlite_sequence;\n")
		for _, row := range sequences {
			fmt.Fprintf(&builder, "INSERT INTO sqlite_sequence VALUES(%s);\n", row)
		}
		builder.WriteString("PRAGMA writable_schema=OFF;\n")
	}
	for _, kind := range []string{"view", "trigger", "index"} {
		for _, object := range objects {
			if object.kind != kind {
				continue
			}
			builder.WriteString(object.sql)
			builder.WriteString(";\n")
		}
	}
	return builder.String(), nil
}

// Replay executes a snapshot against an empty database.
func Replay(ctx context.Context, db *sql.DB, script string) error {
	if strings.TrimSpace(script) == "" {
		return nil
	}
	var enforced int
	restore := false
	// Foreign key enforcement cannot change inside a transaction, so it is
	// suspended before the load and restored afterwards.
	if err := db.QueryRowContext(ctx, "PRAGMA foreign_keys").Scan(&enforced); err == nil && enforced != 0 {
		if _, err := db.ExecContext(ctx, "PRAGMA foreign_keys=OFF"); err != nil {
			return fmt.Errorf("suspend foreign keys: %w", err)
		}
		restore = true
	}
	tx, err := db.BeginTx(ctx, nil)
	if err != nil {
		return fmt.Errorf("replay snapshot: %w", err)
	}
	if err := sqlscript.Exec(ctx, tx, script); err != nil {
		_ = tx.Rollback()
		return fmt.Errorf("replay snapshot: %w", err)
	}
	if err := tx.Commit(); err != nil {
		return fmt.Errorf("replay snapshot: %w", err)
	}
	if restore {
		if _, err := db.ExecContext(ctx, "PRAGMA foreign_keys=ON"); err != nil {
			return fmt.Errorf("restore foreign keys: %w", err)
		}
	}
	return nil
}

type schemaObject struct {
	kind string
	name string
	sql  string
}

func schemaObjects(ctx context.Context, db *sql.DB) ([]schemaObject, error) {
	rows, err := db.QueryContext(ctx, `SELECT type, name, sql FROM sqlite_master
		WHERE sql IS NOT NULL AND name NOT LIKE 'sqlite\_%' ESCAPE '\'
		ORDER BY type, name`)
	if err != nil {
		return nil, fmt.Errorf("read schema: %w", err)
	}
	defer rows.Close()
	var objects []schemaObject
	for rows.Next() {
		var object schemaObject
		if err := rows.Scan(&object.kind, &object.name, &object.sql); err != nil {
			return nil, fmt.Errorf("read schema: %w", err)
		}
		objects = append(objects, object)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("read schema: %w", err)
	}
	return objects, nil
}

// tableRows renders every row as a comma-separated SQL literal list. The SQLite
// quote function produces the literal, so BLOB, NULL, TEXT, and REAL values
// round-trip without a Go-side encoder.
func tableRows(ctx context.Context, db *sql.DB, table string) ([]string, error) {
	columns, err := tableColumns(ctx, db, table)
	if err != nil {
		return nil, err
	}
	if len(columns) == 0 {
		return nil, nil
	}
	quoted := make([]string, 0, len(columns))
	for _, column := range columns {
		quoted = append(quoted, "quote("+quoteIdentifier(column)+")")
	}
	projection := strings.Join(quoted, ", ")
	rows, err := db.QueryContext(ctx,
		fmt.Sprintf("SELECT %s FROM %s ORDER BY rowid", projection, quoteIdentifier(table)))
	if err != nil {
		// A WITHOUT ROWID table has no rowid to order by.
		rows, err = db.QueryContext(ctx,
			fmt.Sprintf("SELECT %s FROM %s", projection, quoteIdentifier(table)))
		if err != nil {
			return nil, fmt.Errorf("read %s: %w", table, err)
		}
	}
	defer rows.Close()
	var rendered []string
	for rows.Next() {
		values := make([]any, len(columns))
		pointers := make([]any, len(columns))
		for index := range values {
			pointers[index] = &values[index]
		}
		if err := rows.Scan(pointers...); err != nil {
			return nil, fmt.Errorf("read %s: %w", table, err)
		}
		literals := make([]string, len(values))
		for index, value := range values {
			literals[index] = literalString(value)
		}
		rendered = append(rendered, strings.Join(literals, ","))
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("read %s: %w", table, err)
	}
	return rendered, nil
}

func literalString(value any) string {
	switch typed := value.(type) {
	case nil:
		return "NULL"
	case string:
		return typed
	case []byte:
		return string(typed)
	default:
		return fmt.Sprint(typed)
	}
}

func tableColumns(ctx context.Context, db *sql.DB, table string) ([]string, error) {
	rows, err := db.QueryContext(ctx, fmt.Sprintf("PRAGMA table_info(%s)", quoteIdentifier(table)))
	if err != nil {
		return nil, fmt.Errorf("read columns of %s: %w", table, err)
	}
	defer rows.Close()
	var columns []string
	for rows.Next() {
		var (
			index        int
			name         string
			declaredType any
			notNull      any
			defaultValue any
			primaryKey   any
		)
		if err := rows.Scan(&index, &name, &declaredType, &notNull, &defaultValue, &primaryKey); err != nil {
			return nil, fmt.Errorf("read columns of %s: %w", table, err)
		}
		columns = append(columns, name)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("read columns of %s: %w", table, err)
	}
	return columns, nil
}

func sequenceRows(ctx context.Context, db *sql.DB) ([]string, error) {
	var present int
	err := db.QueryRowContext(ctx,
		"SELECT count(*) FROM sqlite_master WHERE type='table' AND name=?", sequenceTable).Scan(&present)
	if err != nil {
		return nil, fmt.Errorf("read sequence table: %w", err)
	}
	if present == 0 {
		return nil, nil
	}
	rows, err := db.QueryContext(ctx,
		"SELECT quote(name), quote(seq) FROM sqlite_sequence ORDER BY name")
	if err != nil {
		return nil, fmt.Errorf("read sequence table: %w", err)
	}
	defer rows.Close()
	rendered := []string{}
	for rows.Next() {
		var name, seq any
		if err := rows.Scan(&name, &seq); err != nil {
			return nil, fmt.Errorf("read sequence table: %w", err)
		}
		rendered = append(rendered, literalString(name)+","+literalString(seq))
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("read sequence table: %w", err)
	}
	return rendered, nil
}

func quoteIdentifier(name string) string {
	return `"` + strings.ReplaceAll(name, `"`, `""`) + `"`
}
