// Code generated by configbind/codegen; DO NOT EDIT.

package firestore

import (
	"fmt"
	"strconv"
	"time"

	"github.com/shibukawa/tinybind-go/cliparser"
	"github.com/shibukawa/tinybind-go/configbind"
)

func init() {
	registerConfigDefinition0()
}

func registerConfigDefinition0() {
	configbind.Register[Config](configbind.Definition{
		TypeName: "github.com/shibukawa/popcornwave/database/firestore.Config",
		Prefix:   "middleware.firestore",
		Doc:      "Config is the [middleware.firestore] runtime binding. It is registered when this package is imported, so a project that does not use Firestore gains no key",
		KnownKeys: []string{
			"middleware.firestore.enabled",
			"middleware.firestore.project_id",
			"middleware.firestore.database",
			"middleware.firestore.namespace",
			"middleware.firestore.endpoint",
			"middleware.firestore.credentials",
			"middleware.firestore.credentials_file",
			"middleware.firestore.timeout",
			"middleware.firestore.max_idle_conns",
		},
		Defaults: map[string]string{
			"middleware.firestore.credentials":    "service_account",
			"middleware.firestore.timeout":        "10s",
			"middleware.firestore.max_idle_conns": "4",
		},
		FlagMetas: []cliparser.FieldMeta{
			{Prefix: "middleware.firestore", Key: "enabled", Help: "Enabled opens the client and installs the middleware", Kind: cliparser.KindBool},
			{Prefix: "middleware.firestore", Key: "project_id", Help: "ProjectID names the Google Cloud project. Empty falls back to GOOGLE_CLOUD_PROJECT and then DATASTORE_PROJECT_ID"},
			{Prefix: "middleware.firestore", Key: "database", Help: "Database names a non-default database in that project. Empty selects the project's default database"},
			{Prefix: "middleware.firestore", Key: "namespace", Help: "Namespace scopes every key this process writes and reads"},
			{Prefix: "middleware.firestore", Key: "endpoint", Help: "Endpoint overrides the Datastore host, which is how the emulator is reached"},
			{Prefix: "middleware.firestore", Key: "credentials", Help: "token source: service_account, metadata, oauth2 or static"},
			{Prefix: "middleware.firestore", Key: "credentials_file", Help: "CredentialsFile is the service account key. Empty falls back to GOOGLE_APPLICATION_CREDENTIALS"},
			{Prefix: "middleware.firestore", Key: "timeout", Help: "Timeout bounds one request"},
			{Prefix: "middleware.firestore", Key: "max_idle_conns", Help: "MaxIdleConns sizes the connection pool. The rule of thumb is the expected concurrency"},
		},
		Apply: applyConfigDefinition0,
		Scaffold: []configbind.ScaffoldField{
			{Key: "enabled", Kind: configbind.ScaffoldBool, Help: "Enabled opens the client and installs the middleware"},
			{Key: "project_id", Kind: configbind.ScaffoldString, Help: "ProjectID names the Google Cloud project. Empty falls back to GOOGLE_CLOUD_PROJECT and then DATASTORE_PROJECT_ID"},
			{Key: "database", Kind: configbind.ScaffoldString, Help: "Database names a non-default database in that project. Empty selects the project's default database"},
			{Key: "namespace", Kind: configbind.ScaffoldString, Help: "Namespace scopes every key this process writes and reads"},
			{Key: "endpoint", Kind: configbind.ScaffoldString, Help: "Endpoint overrides the Datastore host, which is how the emulator is reached"},
			{Key: "credentials", Kind: configbind.ScaffoldString, Default: "service_account", Help: "token source: service_account, metadata, oauth2 or static"},
			{Key: "credentials_file", Kind: configbind.ScaffoldString, Help: "CredentialsFile is the service account key. Empty falls back to GOOGLE_APPLICATION_CREDENTIALS"},
			{Key: "timeout", Kind: configbind.ScaffoldDuration, Default: "10s", Help: "Timeout bounds one request"},
			{Key: "max_idle_conns", Kind: configbind.ScaffoldInt, Default: "4", Help: "MaxIdleConns sizes the connection pool. The rule of thumb is the expected concurrency"},
		},
	})
}

func applyConfigDefinition0(dst any, o *configbind.Overlay) error {
	p, ok := dst.(*Config)
	if !ok || p == nil {
		return fmt.Errorf("configbind: apply Config: bad destination")
	}
	if v, ok := o.GetString("middleware.firestore.enabled"); ok {
		bb, err := strconv.ParseBool(v)
		if err != nil {
			return fmt.Errorf("configbind: middleware.firestore.enabled: %w", err)
		}
		p.Enabled = bb
	}
	if v, ok := o.GetString("middleware.firestore.project_id"); ok {
		p.ProjectID = v
	}
	if v, ok := o.GetString("middleware.firestore.database"); ok {
		p.Database = v
	}
	if v, ok := o.GetString("middleware.firestore.namespace"); ok {
		p.Namespace = v
	}
	if v, ok := o.GetString("middleware.firestore.endpoint"); ok {
		p.Endpoint = v
	}
	if v, ok := o.GetString("middleware.firestore.credentials"); ok {
		p.Credentials = v
	} else {
		p.Credentials = "service_account"
	}
	if v, ok := o.GetString("middleware.firestore.credentials_file"); ok {
		p.CredentialsFile = v
	}
	if v, ok := o.GetString("middleware.firestore.timeout"); ok {
		d, err := time.ParseDuration(v)
		if err != nil {
			return fmt.Errorf("configbind: middleware.firestore.timeout: %w", err)
		}
		p.Timeout = d
	} else {
		p.Timeout = 10000000000 // 10s
	}
	if v, ok := o.GetString("middleware.firestore.max_idle_conns"); ok {
		n, err := strconv.ParseInt(v, 10, 0)
		if err != nil {
			return fmt.Errorf("configbind: middleware.firestore.max_idle_conns: %w", err)
		}
		p.MaxIdleConns = int(n)
	} else {
		p.MaxIdleConns = 4
	}
	return nil
}
