// Code generated by tinybind; DO NOT EDIT.

package id_

import (
	"encoding/json"
	"io"
	"net/http"

	"github.com/shibukawa/tinybind-go"
	"github.com/shibukawa/tinybind-go/jsonbind"
)

func init() {
	httpbind.RegisterBind[renameRequest](bindrenameRequest)
	httpbind.RegisterWrite[renameResponse](writerenameResponse)
}

func decoderenameRequestBytes(data []byte) (renameRequest, error) {
	return decoderenameRequestJSON(json.RawMessage(data))
}

func decoderenameRequestJSON(raw json.RawMessage) (renameRequest, error) {
	var out renameRequest
	m, err := jsonbind.RawJSONMap(raw)
	if err != nil {
		return out, err
	}
	if raw, ok := m["name"]; ok {
		v, err := jsonbind.DecodeJSONString(raw)
		if err != nil {
			return out, jsonbind.FieldError("name", "invalid string", err)
		}
		out.Name = v
	}
	return out, nil
}

func bindrenameRequest(r *http.Request) (renameRequest, error) {
	var out renameRequest
	var presentName bool
	var jsonBody map[string]json.RawMessage
	var formBody map[string]string
	var bodyRead bool
	readBody := func() error {
		if bodyRead {
			return nil
		}
		bodyRead = true
		if httpbind.IsJSONRequest(r) {
			m, err := httpbind.ReadJSONMap(r)
			if err != nil {
				return err
			}
			jsonBody = m
			return nil
		}
		if httpbind.IsFormRequest(r) {
			m, err := httpbind.ParseFormMap(r)
			if err != nil {
				return err
			}
			formBody = m
			return nil
		}
		if httpbind.IsMultipartRequest(r) {
			m, _, err := httpbind.ParseMultipartMap(r)
			if err != nil {
				return err
			}
			formBody = m
			return nil
		}
		return nil
	}
	if qv, ok := httpbind.QueryValue(r, "name"); ok {
		presentName = true
		out.Name = qv
	} else {
		if err := readBody(); err != nil {
			return out, err
		}
		if raw, ok := jsonBody["name"]; ok {
			presentName = true
			v, err := jsonbind.DecodeJSONString(raw)
			if err != nil {
				return out, jsonbind.FieldError("name", "invalid string", err)
			}
			out.Name = v
		} else if formBody != nil {
			if fv, ok := formBody["name"]; ok {
				presentName = true
				out.Name = fv
			}
		}
	}
	var checkFields []httpbind.FieldError
	if !presentName || out.Name == "" {
		checkFields = append(checkFields, httpbind.Field("name", "input", "required"))
	}
	if len(checkFields) > 0 {
		return out, httpbind.Validation(checkFields...)
	}
	return out, nil
}

func encoderenameResponseMap(v renameResponse) map[string]any {
	body := map[string]any{}
	body["name"] = v.Name
	return body
}

func encoderenameResponse(w io.Writer, v renameResponse) error {
	return json.NewEncoder(w).Encode(encoderenameResponseMap(v))
}

func writerenameResponse(w http.ResponseWriter, r *http.Request, v renameResponse) error {
	_ = r
	return httpbind.WriteJSON(w, http.StatusOK, encoderenameResponseMap(v))
}
