// Code generated by tinybind; DO NOT EDIT.

package id_

import (
	"io"
	"net/http"

	"github.com/shibukawa/tinybind-go"
	"github.com/shibukawa/tinybind-go/jsonbind"
)

func init() {
	httpbind.RegisterBind[renameRequest](bindrenameRequest)
	httpbind.RegisterWrite[renameResponse](writerenameResponse)
}

func decoderenameRequestBytes(data []byte) (renameRequest, error) {
	if jsonbind.IsBlank(data) {
		var out renameRequest
		return out, nil
	}
	p := jsonbind.NewParser(data)
	out, err := decoderenameRequestJSON(p)
	if err != nil {
		return out, err
	}
	if err := p.End(); err != nil {
		return out, err
	}
	return out, nil
}

func decoderenameRequestJSON(p *jsonbind.Parser) (renameRequest, error) {
	var out renameRequest
	null, err := p.ObjectStart()
	if err != nil || null {
		return out, err
	}
	for n := 0; ; n++ {
		key, ok, err := p.ObjectKey(n)
		if err != nil {
			return out, err
		}
		if !ok {
			return out, nil
		}
		switch string(key) {
		case "name":
			v, err := p.String()
			if err != nil {
				return out, jsonbind.FieldError("name", "invalid string", err)
			}
			out.Name = v
		default:
			if err := p.SkipValue(); err != nil {
				return out, err
			}
		}
	}
}

func bindrenameRequest(r *http.Request) (renameRequest, error) {
	var out renameRequest
	var presentName bool
	queryVals := httpbind.Queries(r)
	var jsonBody *jsonbind.Object
	var formBody map[string]string
	var bodyRead bool
	readBody := func() error {
		if bodyRead {
			return nil
		}
		bodyRead = true
		var err error
		jsonBody, formBody, _, err = httpbind.ReadBody(r, true, false)
		return err
	}
	if qv, ok := httpbind.QueryLookup(queryVals, "name"); ok {
		presentName = true
		out.Name = qv
	} else {
		if err := readBody(); err != nil {
			return out, err
		}
		if raw, ok := jsonBody.Get("name"); ok {
			presentName = true
			v, err := jsonbind.DecodeJSONString(raw)
			if err != nil {
				return out, jsonbind.FieldError("name", "invalid string", err)
			}
			out.Name = v
		} else if formBody != nil {
			if fv, ok := formBody["name"]; ok {
				presentName = true
				out.Name = fv
			}
		}
	}
	var checkFields []httpbind.FieldError
	if !presentName || out.Name == "" {
		checkFields = append(checkFields, httpbind.Field("name", "input", "required"))
	}
	if len(checkFields) > 0 {
		return out, httpbind.Validation(checkFields...)
	}
	return out, nil
}

func appendrenameResponseJSON(dst []byte, v renameResponse) []byte {
	dst = append(dst, '{')
	dst = append(dst, "\"name\":"...)
	dst = jsonbind.AppendString(dst, v.Name)
	return append(dst, '}')
}

func encoderenameResponse(w io.Writer, v renameResponse) error {
	buf := jsonbind.GetBuffer()
	*buf = appendrenameResponseJSON((*buf)[:0], v)
	*buf = append(*buf, '\n')
	_, err := w.Write(*buf)
	jsonbind.PutBuffer(buf)
	return err
}

func writerenameResponse(w http.ResponseWriter, r *http.Request, v renameResponse) error {
	_ = r
	buf := jsonbind.GetBuffer()
	*buf = appendrenameResponseJSON((*buf)[:0], v)
	err := httpbind.WriteJSONBytes(w, http.StatusOK, *buf)
	jsonbind.PutBuffer(buf)
	return err
}
