// Code generated by tinybind; DO NOT EDIT.

package id_

import (
	"io"
	"net/http"

	"github.com/shibukawa/tinybind-go"
	"github.com/shibukawa/tinybind-go/jsonbind"
)

func init() {
	httpbind.RegisterBind[renameRequest](bindrenameRequest)
	httpbind.RegisterWrite[renameResponse](writerenameResponse)
	jsonbind.RegisterEncode[Profile](encodeProfile)
	jsonbind.RegisterAppend[Profile](appendProfileJSON)
	jsonbind.RegisterDecode[actionProfileInput](decodeactionProfileInputBytes)
}

func decoderenameRequestBytes(data []byte) (renameRequest, error) {
	if jsonbind.IsBlank(data) {
		var out renameRequest
		return out, nil
	}
	var p jsonbind.Parser
	p.Reset(data)
	out, err := decoderenameRequestJSON(&p)
	if err != nil {
		return out, err
	}
	if err := p.End(); err != nil {
		return out, err
	}
	return out, nil
}

func decoderenameRequestJSON(p *jsonbind.Parser) (renameRequest, error) {
	var out renameRequest
	null, err := p.ObjectStart()
	if err != nil || null {
		return out, err
	}
	for n := 0; ; n++ {
		key, ok, err := p.ObjectKey(n)
		if err != nil {
			return out, err
		}
		if !ok {
			return out, nil
		}
		switch string(key) {
		case "name":
			v, err := p.String()
			if err != nil {
				return out, jsonbind.FieldError("name", "invalid string", err)
			}
			out.Name = v
		default:
			if err := p.SkipValue(); err != nil {
				return out, err
			}
		}
	}
}

func bindrenameRequest(r *http.Request) (renameRequest, error) {
	var out renameRequest
	var presentName bool
	queryVals := httpbind.Queries(r)
	needName := true
	if qv, ok := httpbind.QueryLookup(queryVals, "name"); ok {
		needName = false
		presentName = true
		out.Name = qv
	}
	if needName {
		if httpbind.IsJSONRequest(r) {
			data, err := httpbind.ReadJSONBody(r)
			if err != nil {
				return out, err
			}
			if !jsonbind.IsBlank(data) {
				var bodyParser jsonbind.Parser
				bodyParser.Reset(data)
				p := &bodyParser
				null, err := p.ObjectStart()
				if err != nil {
					return out, httpbind.JSONBodyError(err)
				}
				if null {
					return out, httpbind.JSONBodyNotObject()
				}
				for n := 0; ; n++ {
					key, ok, err := p.ObjectKey(n)
					if err != nil {
						return out, httpbind.JSONBodyError(err)
					}
					if !ok {
						break
					}
					switch string(key) {
					case "name":
						if !needName {
							if err := p.SkipValue(); err != nil {
								return out, httpbind.JSONBodyError(err)
							}
							continue
						}
						presentName = true
						v, err := p.String()
						if err != nil {
							return out, jsonbind.FieldError("name", "invalid string", err)
						}
						out.Name = v
					default:
						if err := p.SkipValue(); err != nil {
							return out, httpbind.JSONBodyError(err)
						}
					}
				}
				if err := p.End(); err != nil {
					return out, httpbind.JSONBodyError(err)
				}
			}
		} else {
			formBody, _, err := httpbind.ReadFormBody(r, true, false)
			if err != nil {
				return out, err
			}
			if needName && formBody != nil {
				if fv, ok := formBody["name"]; ok {
					presentName = true
					out.Name = fv
				}
			}
		}
	}
	var checkFields []httpbind.FieldError
	if !presentName || out.Name == "" {
		checkFields = append(checkFields, httpbind.Field("name", "input", "required"))
	}
	if len(checkFields) > 0 {
		return out, httpbind.Validation(checkFields...)
	}
	return out, nil
}

func appendrenameResponseJSON(dst []byte, v renameResponse) []byte {
	dst = append(dst, '{')
	dst = append(dst, "\"name\":"...)
	dst = jsonbind.AppendString(dst, v.Name)
	return append(dst, '}')
}

func encoderenameResponse(w io.Writer, v renameResponse) error {
	buf := jsonbind.GetBuffer()
	*buf = appendrenameResponseJSON((*buf)[:0], v)
	*buf = append(*buf, '\n')
	_, err := w.Write(*buf)
	jsonbind.PutBuffer(buf)
	return err
}

func writerenameResponse(w http.ResponseWriter, r *http.Request, v renameResponse) error {
	_ = r
	buf := jsonbind.GetBuffer()
	*buf = appendrenameResponseJSON((*buf)[:0], v)
	err := httpbind.WriteJSONBytes(w, http.StatusOK, *buf)
	jsonbind.PutBuffer(buf)
	return err
}

func appendProfileJSON(dst []byte, v Profile) []byte {
	dst = append(dst, '{')
	dst = append(dst, "\"id\":"...)
	dst = jsonbind.AppendString(dst, v.Id)
	dst = append(dst, ",\"name\":"...)
	dst = jsonbind.AppendString(dst, v.Name)
	return append(dst, '}')
}

func encodeProfile(w io.Writer, v Profile) error {
	buf := jsonbind.GetBuffer()
	*buf = appendProfileJSON((*buf)[:0], v)
	*buf = append(*buf, '\n')
	_, err := w.Write(*buf)
	jsonbind.PutBuffer(buf)
	return err
}

func decodeactionProfileInputBytes(data []byte) (actionProfileInput, error) {
	if jsonbind.IsBlank(data) {
		var out actionProfileInput
		return out, nil
	}
	var p jsonbind.Parser
	p.Reset(data)
	out, err := decodeactionProfileInputJSON(&p)
	if err != nil {
		return out, err
	}
	if err := p.End(); err != nil {
		return out, err
	}
	return out, nil
}

func decodeactionProfileInputJSON(p *jsonbind.Parser) (actionProfileInput, error) {
	var out actionProfileInput
	null, err := p.ObjectStart()
	if err != nil || null {
		return out, err
	}
	for n := 0; ; n++ {
		key, ok, err := p.ObjectKey(n)
		if err != nil {
			return out, err
		}
		if !ok {
			return out, nil
		}
		switch string(key) {
		case "id":
			v, err := p.String()
			if err != nil {
				return out, jsonbind.FieldError("id", "invalid string", err)
			}
			out.Id = v
		default:
			if err := p.SkipValue(); err != nil {
				return out, err
			}
		}
	}
}

// actionProfileInput is the decoded argument list of the profile server action.
type actionProfileInput struct {
	Id string `json:"id"`
}

// ActionProfile is the generated entry point of the profile server action.
func ActionProfile(w http.ResponseWriter, r *http.Request) {
	body, err := httpbind.ReadActionBody(r)
	if err != nil {
		httpbind.WriteError(w, r, err)
		return
	}
	input, err := decodeactionProfileInputBytes(body)
	if err != nil {
		httpbind.WriteError(w, r, err)
		return
	}
	out, err := profile(r.Context(), input.Id)
	if err != nil {
		httpbind.WriteError(w, r, err)
		return
	}
	buf := jsonbind.GetBuffer()
	*buf = appendProfileJSON((*buf)[:0], out)
	err = httpbind.WriteJSONBytes(w, http.StatusOK, *buf)
	jsonbind.PutBuffer(buf)
	if err != nil {
		httpbind.WriteError(w, r, err)
		return
	}
}
