// Code generated by tinybind HTML templates; DO NOT EDIT.

package id_

import (
	"context"

	"github.com/shibukawa/tinybind-go/htmlbind"
	"github.com/shibukawa/tinybind-go/htmlbind/delta"
)

type PageParams struct {
	Id   string
	Page *int
}

type planPageOpsVal1 struct {
	Outer PageParams
	Name  string
}

var planPageOpsVal1Ops = htmlbind.Builder[planPageOpsVal1]{}

type planPageOpsVal1OpsVal2 struct {
	Outer  planPageOpsVal1
	Number int
}

var planPageOpsVal1OpsVal2Ops = htmlbind.Builder[planPageOpsVal1OpsVal2]{}

var planPageOps = htmlbind.Builder[PageParams]{}

// planPageInput canonically encodes the declared inputs of Page.
// Slot arguments are excluded: their content belongs to the child boundary,
// so a frame stays comparable when only its child changed.
func planPageInput(p PageParams) string {
	return delta.CanonJoin(
		delta.CanonString[string](p.Id),
		delta.CanonOptional(p.Page, delta.CanonInt),
	)
}

var planPageBoundary = &htmlbind.Boundary[PageParams]{
	ComponentID: "id_.page.Page",
	Attr:        "data-tb-id",
	Input:       planPageInput,
}

var planPagePlan = &htmlbind.Plan[PageParams]{
	Head:        []string{"<script src=\"/public/generated/page.script.564ef8d0adbe.js\" type=\"module\"></script>"},
	HeadSources: []string{""},
	Assets:      []htmlbind.Asset{{ID: "page.script.564ef8d0adbe", Type: "text/javascript", URL: "/public/generated/page.script.564ef8d0adbe.js", Scope: "id_.page.Page"}},
	Boundary:    planPageBoundary,
	Ops: []htmlbind.Op[PageParams]{
		htmlbind.ValErrCtx(
			func(ctx context.Context, p PageParams) (string, error) { return LoadName(ctx, p.Id, p.Page) },
			func(p PageParams, value string) planPageOpsVal1 { return planPageOpsVal1{Outer: p, Name: value} },
			[]htmlbind.Op[planPageOpsVal1]{
				htmlbind.Val(
					func(p planPageOpsVal1) int { return PageNumber(p.Outer.Page) },
					func(p planPageOpsVal1, value int) planPageOpsVal1OpsVal2 {
						return planPageOpsVal1OpsVal2{Outer: p, Number: value}
					},
					[]htmlbind.Op[planPageOpsVal1OpsVal2]{
						planPageOpsVal1OpsVal2Ops.Static("   <section"),
						planPageOpsVal1OpsVal2Ops.BoundaryAttr(),
						planPageOpsVal1OpsVal2Ops.Static(" data-tb-component=\"id_.page.Page\"> <h1 data-tb-on=\"click:highlight\">"),
						planPageOpsVal1OpsVal2Ops.Text(func(p planPageOpsVal1OpsVal2) string { return p.Outer.Name }),
						planPageOpsVal1OpsVal2Ops.Static("</h1> <p>page "),
						planPageOpsVal1OpsVal2Ops.Raw(func(p planPageOpsVal1OpsVal2) string { return htmlbind.FormatInt(p.Number) }),
						planPageOpsVal1OpsVal2Ops.Static("</p> <button data-tb-action=\"/_action/00369cf962b6/Rename\" data-target=\"#name\">rename</button> <form data-tb-action=\"/_action/d71506d06c1e/Retire\" method=\"post\"><input type=\"hidden\" name=\"_action\" value=\"d71506d06c1e/Retire\" />"),
						planPageOpsVal1OpsVal2Ops.CSRFField("_csrf"),
						planPageOpsVal1OpsVal2Ops.Static(" <input type=\"text\" name=\"reason\" /> <button type=\"submit\">retire</button> </form> </section> "),
					}),
			}),
	},
}

// Page binds Page to its parameters, producing a renderable fragment.
func Page(params PageParams) htmlbind.Fragment { return htmlbind.Bind(planPagePlan, params) }
