// Code generated by tinybind HTML templates; DO NOT EDIT.

package id_

import (
	"github.com/shibukawa/tinybind-go/htmlbind"
	"github.com/shibukawa/tinybind-go/htmlbind/delta"
)

type PageParams struct {
	Name string
	Page int
}

var planPageOps = htmlbind.Builder[PageParams]{}

// planPageInput canonically encodes the declared inputs of Page.
// Slot arguments are excluded: their content belongs to the child boundary,
// so a frame stays comparable when only its child changed.
func planPageInput(p PageParams) string {
	return delta.CanonJoin(
		delta.CanonString[string](p.Name),
		delta.CanonInt(p.Page),
	)
}

var planPageBoundary = &htmlbind.Boundary[PageParams]{
	ComponentID: "id_.page.Page",
	Attr:        "data-tb-id",
	Input:       planPageInput,
}

var planPagePlan = &htmlbind.Plan[PageParams]{
	Head:        []string{"<script src=\"/public/generated/page.script.564ef8d0adbe.js\" type=\"module\"></script>"},
	HeadSources: []string{""},
	Assets:      []htmlbind.Asset{{ID: "page.script.564ef8d0adbe", Type: "text/javascript", URL: "/public/generated/page.script.564ef8d0adbe.js", Scope: "id_.page.Page"}},
	Boundary:    planPageBoundary,
	Ops: []htmlbind.Op[PageParams]{
		planPageOps.Static("  <section"),
		planPageOps.BoundaryAttr(),
		planPageOps.Static(" data-tb-component=\"id_.page.Page\"> <h1 data-tb-on=\"click:highlight\">"),
		planPageOps.Text(func(p PageParams) string { return p.Name }),
		planPageOps.Static("</h1> <p>page "),
		planPageOps.Raw(func(p PageParams) string { return htmlbind.FormatInt(p.Page) }),
		planPageOps.Static("</p> <button data-tb-action=\"/_action/00369cf962b6/Rename\" data-target=\"#name\">rename</button> <form data-tb-action=\"/_action/d71506d06c1e/Retire\" method=\"post\"><input type=\"hidden\" name=\"_action\" value=\"d71506d06c1e/Retire\" />"),
		planPageOps.CSRFField("_csrf"),
		planPageOps.Static(" <input type=\"text\" name=\"reason\" /> <button type=\"submit\">retire</button> </form> </section> "),
	},
}

// Page binds Page to its parameters, producing a renderable fragment.
func Page(params PageParams) htmlbind.Fragment { return htmlbind.Bind(planPagePlan, params) }
