// Code generated by Popcorn Wave via TinyBind; DO NOT EDIT.

package id_

import (
	"net/http"
	"strconv"

	"github.com/shibukawa/popcornwave/pw"
)

// RouteParams holds the URL inputs of GET /users/{id}.
type RouteParams struct {
	ID   string
	Page *int
}

// DecodeRoute reads the path and query values of GET /users/{id}.
// An unparsable value produces an error rather than a zero value.
func DecodeRoute(r *http.Request) (RouteParams, error) {
	var out RouteParams
	query := r.URL.Query()
	rawID := r.PathValue("id")
	if rawID == "" {
		return out, pw.BadRequest(pw.Problem{Code: "missing_path_parameter", Message: "missing path parameter id"})
	}
	out.ID = rawID
	if raw := query.Get("page"); raw != "" {
		v, err := strconv.Atoi(raw)
		if err != nil {
			return out, pw.BadRequest(pw.Problem{Code: "invalid_query_parameter", Message: "query parameter page is not a valid int"}, err)
		}
		value := v
		out.Page = &value
	}
	return out, nil
}
