package pwgen

import "github.com/shibukawa/tinybind-go/routetree"

const pwPagePackage = "github.com/shibukawa/popcornwave/pwpage"

// GeneratedHeaderPrefix is what every file Popcorn Wave generates leads with,
// whichever writer produced it. Discovery is told to skip a file carrying it,
// because generated code is output rather than input: a generated page registry
// read back as a source turns every page into a documented API route.
const GeneratedHeaderPrefix = "Code generated by Popcorn Wave"

// PageGeneratedHeader is the first line of every page tree file.
const PageGeneratedHeader = "// " + GeneratedHeaderPrefix + " via TinyBind; DO NOT EDIT."

// Attributes the lowerings write, which the framework runtime is what reads.
//
// None of the three follows the emitter's data attribute prefix on its own:
// that option renames the boundary and declaration markers, and these are
// literals it does not reach. Left at their upstream defaults while the prefix
// was branded, a page would carry two spellings and the runtime would need a
// second constant to find half of them.
//
// So they are derived from the same prefix as everything else rather than
// branded here. The runtime builds every attribute name it reads from one
// configured value, and one document holding one spelling is what makes that
// possible. Whether that value stays the module's default or becomes this
// framework's brand is the open decision pwAttributePrefix records; taking it
// moves these three with it, which is the point of deriving them.
const (
	// PageActionAttr is where a lowered server-action writes its endpoint. The
	// rest of the element is left alone, so what a click does beyond posting
	// there stays the application's markup.
	//
	// It was spelled with this framework's brand while nothing read it. That
	// was affordable then and is not now: the runtime resolves it beside the
	// boundary attributes, from the same prefix, in the same lookup.
	PageActionAttr = "data-" + pwAttributePrefix + "-action"
	// PageClientHandlerAttr lists the events an element binds and the handler
	// each names, as one comma-separated list of colon-separated pairs.
	PageClientHandlerAttr = "data-" + pwAttributePrefix + "-on"
	// PageComponentParamAttr carries the JSON object of the parameters a
	// component's script block asked for.
	PageComponentParamAttr = "data-" + pwAttributePrefix + "-props"
)

// Reserved file names of a page tree. TinyBind names them .tb.html; a Popcorn
// Wave project spells every template .pw.html, so these are configured rather
// than defaulted.
const (
	PageFile     = "page.pw.html"
	LayoutFile   = "layout.pw.html"
	DocumentFile = "document.pw.html"
)

// Generated file names of a page tree. They end in _pw_gen.go like every other
// generated file, so the .gitignore and editor rules a project already has
// cover them with nothing added.
const (
	PageComponentSuffix = "_pw_gen.go"
	PageDecoderOutput   = "route_pw_gen.go"
	PageRegistryOutput  = "routes_pw_gen.go"
)

// pageRenderBlock is the one generation template Popcorn Wave replaces.
//
// Symbols repoint a package but never a signature, and the built-in call writes
// into an io.Writer with no request in hand. Every response decision the
// framework owns — the document shell, bot classification, whether the page
// streams, the encoding, which error page answers a failure — needs the request,
// so the call is reshaped rather than renamed.
const pageRenderBlock = `{{ .Symbols.RuntimeAlias }}.Render({{ .Writer }}, {{ .Request }}, {{ .Chain }}, {{ .Leaf }}{{ with .Options }}, {{ . }}...{{ end }})`

// setActionAdmission says which functions of a route package are server
// actions: this framework's annotation admits one, and nothing this framework
// generated is looked at.
//
// The annotation's identifier is declared rather than derived because a path's
// last element is not always the package name: the module's path ends in
// tinybind-go and its package is httpbind, which is what made the module state
// this at all. Ours agree, and saying so is what keeps a project from importing
// a second module to declare an action.
//
// The header is registered for the reason options.GeneratedHeaders is: a file
// this framework wrote is output rather than input. TinyBind recognizes its own
// prefix unprompted, so what is listed here is only ever this framework's own —
// which is what keeps the arrangement from going stale when the module renames
// its header.
func setActionAdmission(shape *routetree.HandlerShape, importPath, pkg string) {
	shape.Declaration = routetree.ActionDeclaration{
		Import:  importPath,
		Package: pkg,
		Name:    "ServerAction",
	}
	shape.GeneratedHeaders = []string{GeneratedHeaderPrefix}
}

// setBehaviourAttrs points every lowered behaviour attribute at this framework's
// namespace.
//
// All three together, because they are one namespace and a project reading two
// of them off one element is the failure this prevents. Both emitters call it,
// so the net/http and fasthttp trees cannot drift apart on what the runtime
// reads.
func setBehaviourAttrs(emitter *routetree.Emitter) {
	emitter.ActionAttr = PageActionAttr
	emitter.ClientHandlerAttr = PageClientHandlerAttr
	emitter.ComponentParameterAttr = PageComponentParamAttr
}

// PageEmitter returns the emitter that writes a page tree.
func PageEmitter() (*routetree.Emitter, error) {
	emitter := routetree.NewEmitter()

	// The runtime supplies the wrapper type, the option type, and the render
	// entry. The router type comes from the same package but is not imported
	// again: MuxType is written verbatim, and an empty MuxImport keeps the
	// registry from emitting the import twice.
	emitter.Symbols.RuntimeImport = pwPagePackage
	emitter.Symbols.RuntimeAlias = "pwpage"
	emitter.Symbols.MuxImport = ""
	emitter.Symbols.MuxAlias = ""
	emitter.Symbols.MuxType = "pwpage.Router"
	// An interface is not something generated code can build, so no constructor
	// is emitted; an application creates its mux with pw.NewServeMux.
	emitter.Symbols.MuxConstructor = ""

	// The error values are pw's ordinary public API. Problem already carries the
	// Code and Message fields the decoder writes, and BadRequest returns one
	// given one, so the error block needs no override at all.
	emitter.Symbols.ErrorImport = pwPackage
	emitter.Symbols.ErrorAlias = "pw"
	emitter.Symbols.WriteError = "WriteProblem"

	// The two admission rules travel together: a function is an action by
	// having the handler shape or by being declared, and this is where both are
	// stated for one transport.
	shape := routetree.DefaultHandlerShape()
	setActionAdmission(&shape, pwPackage, "pw")
	emitter.HandlerShape = shape

	emitter.GeneratedHeader = PageGeneratedHeader
	emitter.RenderWriterType = "http.ResponseWriter"
	emitter.RenderRequestParam = "r"

	setBehaviourAttrs(emitter)

	if err := emitter.Parse(routetree.TemplateRender, pageRenderBlock); err != nil {
		return nil, err
	}
	return emitter, nil
}

// PageConfig returns the discovery configuration for one tree.
func PageConfig(root, importBase string) routetree.Config {
	return routetree.Config{
		Root:         root,
		ImportBase:   importBase,
		PageFile:     PageFile,
		LayoutFile:   LayoutFile,
		DocumentFile: DocumentFile,
	}
}

const (
	pwFastPackage     = "github.com/shibukawa/popcornwave/pwfast"
	pwFastPagePackage = "github.com/shibukawa/popcornwave/pwfastpage"
	fastHTTPPackage   = "github.com/shibukawa/tinygodriver/fasthttp"
)

// fastPageRenderBlock is the render call on the second transport.
//
// One value carries the response and the request, so where the net/http block
// writes two leading arguments this writes one. The rest is identical, which is
// the point: the same chain, the same leaf, the same options.
const fastPageRenderBlock = `{{ .Symbols.RuntimeAlias }}.Render({{ .Request }}, {{ .Chain }}, {{ .Leaf }}{{ with .Options }}, {{ . }}...{{ end }})`

// FastPageEmitter returns the emitter that writes a page tree for the second
// transport.
//
// It is a second configuration rather than a second template set. Everything
// that differs is a symbol: which package supplies the router, the error
// constructors and the request accessors; how a handler's parameters are
// spelled; and the two pattern spellings a trie router does not share with Go
// 1.22. The templates are upstream's, unchanged.
func FastPageEmitter() (*routetree.Emitter, error) {
	emitter := routetree.NewEmitter()

	emitter.Symbols.RuntimeImport = pwFastPagePackage
	emitter.Symbols.RuntimeAlias = "pwfastpage"
	emitter.Symbols.MuxImport = ""
	emitter.Symbols.MuxAlias = ""
	emitter.Symbols.MuxType = "pwfastpage.Router"
	emitter.Symbols.MuxConstructor = ""

	// The request accessors and the error constructors are both pwfast's, so
	// one alias serves the decoder and the failure path.
	emitter.Symbols.ErrorImport = pwFastPackage
	emitter.Symbols.ErrorAlias = "pwfast"
	emitter.Symbols.WriteError = "WriteProblem"

	// The transport itself is named only for the handler's parameter type.
	emitter.Symbols.HTTPImport = fastHTTPPackage
	emitter.Symbols.HTTPAlias = "fasthttp"
	emitter.Symbols.RequestType = "*fasthttp.RequestCtx"
	emitter.Symbols.HandlerParams = "r *fasthttp.RequestCtx"
	// One value carries both halves, so the writer and the request are the same
	// identifier. That is what collapses the leading arguments of a runtime
	// call rather than a rule about how many to write.
	emitter.Symbols.Writer = "r"
	emitter.Symbols.Request = "r"
	// The request value is itself a context, so a generated decoder reaches the
	// context without a .Context() call.
	emitter.Symbols.RequestIsContext = true

	// The two spellings a trie router does not share with Go 1.22. Getting
	// these wrong does not fail: the router reads "{rest...}" as a parameter
	// named "rest..." and "{$}" as one named "$", and installs the route
	// somewhere else without complaining.
	emitter.Symbols.CatchAllSuffix = ":*"
	emitter.Symbols.RootPattern = "/"

	// A page function written against this transport takes one parameter, and a
	// recognizer keyed on net/http would read it as a malformed typed page and
	// report a signature error for a declaration that is correct.
	fastShape := routetree.FastHTTPHandlerShape(fastHTTPPackage)
	setActionAdmission(&fastShape, pwFastPackage, "pwfast")
	emitter.HandlerShape = fastShape

	emitter.GeneratedHeader = PageGeneratedHeader
	emitter.RenderWriterType = "io.Writer"
	emitter.RenderRequestParam = "r"
	setBehaviourAttrs(emitter)

	if err := emitter.Parse(routetree.TemplateRender, fastPageRenderBlock); err != nil {
		return nil, err
	}
	return emitter, nil
}
