package pwgen

import "github.com/shibukawa/tinybind-go/routetree"

const pwPagePackage = "github.com/shibukawa/popcornwave/pwpage"

// GeneratedHeaderPrefix is what every file Popcorn Wave generates leads with,
// whichever writer produced it. Discovery is told to skip a file carrying it,
// because generated code is output rather than input: a generated page registry
// read back as a source turns every page into a documented API route.
const GeneratedHeaderPrefix = "Code generated by Popcorn Wave"

// PageGeneratedHeader is the first line of every page tree file.
const PageGeneratedHeader = "// " + GeneratedHeaderPrefix + " via TinyBind; DO NOT EDIT."

// PageActionAttr is the attribute a lowered server-action writes. The framework
// runtime resolves it; the rest of the element is left alone, so what a click
// does beyond posting there stays the application's markup.
const PageActionAttr = "data-pw-action"

// Reserved file names of a page tree. TinyBind names them .tb.html; a Popcorn
// Wave project spells every template .pw.html, so these are configured rather
// than defaulted.
const (
	PageFile     = "page.pw.html"
	LayoutFile   = "layout.pw.html"
	DocumentFile = "document.pw.html"
)

// Generated file names of a page tree. They end in _pw_gen.go like every other
// generated file, so the .gitignore and editor rules a project already has
// cover them with nothing added.
const (
	PageComponentSuffix = "_pw_gen.go"
	PageDecoderOutput   = "route_pw_gen.go"
	PageRegistryOutput  = "routes_pw_gen.go"
)

// pageRenderBlock is the one generation template Popcorn Wave replaces.
//
// Symbols repoint a package but never a signature, and the built-in call writes
// into an io.Writer with no request in hand. Every response decision the
// framework owns — the document shell, bot classification, whether the page
// streams, the encoding, which error page answers a failure — needs the request,
// so the call is reshaped rather than renamed.
const pageRenderBlock = `{{ .Symbols.RuntimeAlias }}.Render({{ .Writer }}, {{ .Request }}, {{ .Chain }}, {{ .Leaf }}{{ with .Options }}, {{ . }}...{{ end }})`

// PageEmitter returns the emitter that writes a page tree.
func PageEmitter() (*routetree.Emitter, error) {
	emitter := routetree.NewEmitter()

	// The runtime supplies the wrapper type, the option type, and the render
	// entry. The router type comes from the same package but is not imported
	// again: MuxType is written verbatim, and an empty MuxImport keeps the
	// registry from emitting the import twice.
	emitter.Symbols.RuntimeImport = pwPagePackage
	emitter.Symbols.RuntimeAlias = "pwpage"
	emitter.Symbols.MuxImport = ""
	emitter.Symbols.MuxAlias = ""
	emitter.Symbols.MuxType = "pwpage.Router"
	// An interface is not something generated code can build, so no constructor
	// is emitted; an application creates its mux with pw.NewServeMux.
	emitter.Symbols.MuxConstructor = ""

	// The error values are pw's ordinary public API. Problem already carries the
	// Code and Message fields the decoder writes, and BadRequest returns one
	// given one, so the error block needs no override at all.
	emitter.Symbols.ErrorImport = pwPackage
	emitter.Symbols.ErrorAlias = "pw"
	emitter.Symbols.WriteError = "WriteProblem"

	emitter.GeneratedHeader = PageGeneratedHeader
	emitter.RenderWriterType = "http.ResponseWriter"
	emitter.RenderRequestParam = "r"

	// A lowered server-action writes this attribute, and the framework runtime
	// is what reads it. Leaving the upstream default would put another module's
	// namespace on a page whose script, reserved paths, and generated files are
	// all pw's.
	emitter.ActionAttr = PageActionAttr

	if err := emitter.Parse(routetree.TemplateRender, pageRenderBlock); err != nil {
		return nil, err
	}
	return emitter, nil
}

// PageConfig returns the discovery configuration for one tree.
func PageConfig(root, importBase string) routetree.Config {
	return routetree.Config{
		Root:         root,
		ImportBase:   importBase,
		PageFile:     PageFile,
		LayoutFile:   LayoutFile,
		DocumentFile: DocumentFile,
	}
}
