// Code generated by configbind/codegen; DO NOT EDIT.

package auth

import (
	"fmt"
	"strconv"

	"github.com/shibukawa/tinybind-go/cliparser"
	"github.com/shibukawa/tinybind-go/configbind"
)

func init() {
	registerConfigDefinition0()
}

func registerConfigDefinition0() {
	configbind.Register[Config](configbind.Definition{
		TypeName: "github.com/shibukawa/popcornwave/plugin/auth.Config",
		Prefix:   "auth",
		Doc:      "Config is the [auth] runtime binding. It is registered when this package is imported",
		KnownKeys: []string{
			"auth.enabled",
			"auth.mode",
			"auth.login_path",
			"auth.callback_path",
			"auth.logout_path",
			"auth.post_login_path",
			"auth.protection.include",
			"auth.protection.exclude",
			"auth.protection.unauthenticated",
			"auth.oidc.issuer",
			"auth.oidc.client_id",
			"auth.oidc.client_secret",
			"auth.oidc.redirect_url",
			"auth.oidc.scopes",
			"auth.oidc.identity_claim",
			"auth.oidc.admission",
			"auth.oidc.auto_provision",
			"auth.oidc.claim.path",
			"auth.oidc.claim.values",
			"auth.oidc.claim.match",
			"auth.oidc.registered_claims",
			"auth.oidc.provider_logout",
			"auth.oidc.allow_loopback_http",
		},
		Defaults: map[string]string{
			"auth.enabled":                    "false",
			"auth.mode":                       "oidc_only",
			"auth.login_path":                 "/auth/login",
			"auth.callback_path":              "/auth/callback",
			"auth.logout_path":                "/auth/logout",
			"auth.post_login_path":            "/",
			"auth.protection.unauthenticated": "redirect",
			"auth.oidc.identity_claim":        "sub",
			"auth.oidc.admission":             "authenticated",
			"auth.oidc.auto_provision":        "true",
			"auth.oidc.claim.match":           "any",
			"auth.oidc.provider_logout":       "true",
			"auth.oidc.allow_loopback_http":   "false",
		},
		DependsOn: map[string][]string{
			"auth.mode":                       {"auth.enabled"},
			"auth.login_path":                 {"auth.enabled"},
			"auth.callback_path":              {"auth.enabled"},
			"auth.logout_path":                {"auth.enabled"},
			"auth.post_login_path":            {"auth.enabled"},
			"auth.protection.include":         {"auth.enabled"},
			"auth.protection.exclude":         {"auth.enabled"},
			"auth.protection.unauthenticated": {"auth.enabled"},
			"auth.oidc.issuer":                {"auth.enabled"},
			"auth.oidc.client_id":             {"auth.enabled"},
			"auth.oidc.client_secret":         {"auth.enabled"},
			"auth.oidc.redirect_url":          {"auth.enabled"},
			"auth.oidc.scopes":                {"auth.enabled"},
			"auth.oidc.identity_claim":        {"auth.enabled"},
			"auth.oidc.admission":             {"auth.enabled"},
			"auth.oidc.auto_provision":        {"auth.enabled"},
			"auth.oidc.claim.path":            {"auth.enabled"},
			"auth.oidc.claim.values":          {"auth.enabled"},
			"auth.oidc.claim.match":           {"auth.enabled"},
			"auth.oidc.registered_claims":     {"auth.enabled"},
			"auth.oidc.provider_logout":       {"auth.enabled"},
			"auth.oidc.allow_loopback_http":   {"auth.enabled"},
		},
		Secrets: map[string]string{
			"auth.oidc.client_secret": "mask",
		},
		FlagMetas: []cliparser.FieldMeta{
			{Prefix: "auth", Key: "enabled", Kind: cliparser.KindBool},
			{Prefix: "auth", Key: "mode", Help: "oidc_only"},
			{Prefix: "auth", Key: "login_path", Help: "path that starts the provider flow"},
			{Prefix: "auth", Key: "callback_path"},
			{Prefix: "auth", Key: "logout_path"},
			{Prefix: "auth", Key: "post_login_path", Help: "path a completed login lands on"},
			{Prefix: "auth", Key: "protection.include", Help: "protected path pattern", Kind: cliparser.KindArray},
			{Prefix: "auth", Key: "protection.exclude", Help: "public path pattern", Kind: cliparser.KindArray},
			{Prefix: "auth", Key: "protection.unauthenticated", Help: "redirect or unauthorized"},
			{Prefix: "auth", Key: "oidc.issuer", Env: "AUTH_OIDC_ISSUER"},
			{Prefix: "auth", Key: "oidc.client_id", Env: "AUTH_OIDC_CLIENT_ID"},
			{Prefix: "auth", Key: "oidc.client_secret", Env: "AUTH_OIDC_CLIENT_SECRET"},
			{Prefix: "auth", Key: "oidc.redirect_url"},
			{Prefix: "auth", Key: "oidc.scopes", Kind: cliparser.KindArray},
			{Prefix: "auth", Key: "oidc.identity_claim", Help: "verified claim that identifies a local account"},
			{Prefix: "auth", Key: "oidc.admission", Help: "authenticated, claim, registered, or existing"},
			{Prefix: "auth", Key: "oidc.auto_provision", Help: "AutoProvision permits an unknown verified identity to create an account through the registered account resolver", Kind: cliparser.KindBool},
			{Prefix: "auth", Key: "oidc.claim.path", Help: "JSON Pointer into verified claims"},
			{Prefix: "auth", Key: "oidc.claim.values", Kind: cliparser.KindArray},
			{Prefix: "auth", Key: "oidc.claim.match", Help: "any or all"},
			{Prefix: "auth", Key: "oidc.registered_claims", Help: "claims compared against the allowlist; defaults to identity_claim", Kind: cliparser.KindArray},
			{Prefix: "auth", Key: "oidc.provider_logout", Help: "also end the provider session on logout", Kind: cliparser.KindBool},
			{Prefix: "auth", Key: "oidc.allow_loopback_http", Help: "permit an http loopback issuer during development", Kind: cliparser.KindBool},
		},
		Apply: applyConfigDefinition0,
		Scaffold: []configbind.ScaffoldField{
			{Key: "enabled", Kind: configbind.ScaffoldBool, Default: "false"},
			{Key: "mode", Kind: configbind.ScaffoldString, Default: "oidc_only", Help: "oidc_only"},
			{Key: "login_path", Kind: configbind.ScaffoldString, Default: "/auth/login", Help: "path that starts the provider flow"},
			{Key: "callback_path", Kind: configbind.ScaffoldString, Default: "/auth/callback"},
			{Key: "logout_path", Kind: configbind.ScaffoldString, Default: "/auth/logout"},
			{Key: "post_login_path", Kind: configbind.ScaffoldString, Default: "/", Help: "path a completed login lands on"},
			{Key: "protection.include", Kind: configbind.ScaffoldStringSlice, Help: "protected path pattern"},
			{Key: "protection.exclude", Kind: configbind.ScaffoldStringSlice, Help: "public path pattern"},
			{Key: "protection.unauthenticated", Kind: configbind.ScaffoldString, Default: "redirect", Help: "redirect or unauthorized"},
			{Key: "oidc.issuer", Kind: configbind.ScaffoldString, Env: "AUTH_OIDC_ISSUER"},
			{Key: "oidc.client_id", Kind: configbind.ScaffoldString, Env: "AUTH_OIDC_CLIENT_ID"},
			{Key: "oidc.client_secret", Kind: configbind.ScaffoldString, Env: "AUTH_OIDC_CLIENT_SECRET"},
			{Key: "oidc.redirect_url", Kind: configbind.ScaffoldString},
			{Key: "oidc.scopes", Kind: configbind.ScaffoldStringSlice},
			{Key: "oidc.identity_claim", Kind: configbind.ScaffoldString, Default: "sub", Help: "verified claim that identifies a local account"},
			{Key: "oidc.admission", Kind: configbind.ScaffoldString, Default: "authenticated", Help: "authenticated, claim, registered, or existing"},
			{Key: "oidc.auto_provision", Kind: configbind.ScaffoldBool, Default: "true", Help: "AutoProvision permits an unknown verified identity to create an account through the registered account resolver"},
			{Key: "oidc.claim.path", Kind: configbind.ScaffoldString, Help: "JSON Pointer into verified claims"},
			{Key: "oidc.claim.values", Kind: configbind.ScaffoldStringSlice},
			{Key: "oidc.claim.match", Kind: configbind.ScaffoldString, Default: "any", Help: "any or all"},
			{Key: "oidc.registered_claims", Kind: configbind.ScaffoldStringSlice, Help: "claims compared against the allowlist; defaults to identity_claim"},
			{Key: "oidc.provider_logout", Kind: configbind.ScaffoldBool, Default: "true", Help: "also end the provider session on logout"},
			{Key: "oidc.allow_loopback_http", Kind: configbind.ScaffoldBool, Default: "false", Help: "permit an http loopback issuer during development"},
		},
	})
}

func applyConfigDefinition0(dst any, o *configbind.Overlay) error {
	p, ok := dst.(*Config)
	if !ok || p == nil {
		return fmt.Errorf("configbind: apply Config: bad destination")
	}
	if v, ok := o.GetString("auth.enabled"); ok {
		bb, err := strconv.ParseBool(v)
		if err != nil {
			return fmt.Errorf("configbind: auth.enabled: %w", err)
		}
		p.Enabled = bb
	} else {
		p.Enabled = false
	}
	if v, ok := o.GetString("auth.mode"); ok {
		p.Mode = v
	} else {
		p.Mode = "oidc_only"
	}
	if v, ok := o.GetString("auth.login_path"); ok {
		p.LoginPath = v
	} else {
		p.LoginPath = "/auth/login"
	}
	if v, ok := o.GetString("auth.callback_path"); ok {
		p.CallbackPath = v
	} else {
		p.CallbackPath = "/auth/callback"
	}
	if v, ok := o.GetString("auth.logout_path"); ok {
		p.LogoutPath = v
	} else {
		p.LogoutPath = "/auth/logout"
	}
	if v, ok := o.GetString("auth.post_login_path"); ok {
		p.PostLoginPath = v
	} else {
		p.PostLoginPath = "/"
	}
	if v, ok := o.GetMulti("auth.protection.include"); ok {
		p.Protection.Include = v
	}
	if v, ok := o.GetMulti("auth.protection.exclude"); ok {
		p.Protection.Exclude = v
	}
	if v, ok := o.GetString("auth.protection.unauthenticated"); ok {
		p.Protection.Unauthenticated = v
	} else {
		p.Protection.Unauthenticated = "redirect"
	}
	if v, ok := o.GetString("auth.oidc.issuer"); ok {
		p.OIDC.Issuer = v
	}
	if v, ok := o.GetString("auth.oidc.client_id"); ok {
		p.OIDC.ClientID = v
	}
	if v, ok := o.GetString("auth.oidc.client_secret"); ok {
		p.OIDC.ClientSecret = v
	}
	if v, ok := o.GetString("auth.oidc.redirect_url"); ok {
		p.OIDC.RedirectURL = v
	}
	if v, ok := o.GetMulti("auth.oidc.scopes"); ok {
		p.OIDC.Scopes = v
	}
	if v, ok := o.GetString("auth.oidc.identity_claim"); ok {
		p.OIDC.IdentityClaim = v
	} else {
		p.OIDC.IdentityClaim = "sub"
	}
	if v, ok := o.GetString("auth.oidc.admission"); ok {
		p.OIDC.Admission = v
	} else {
		p.OIDC.Admission = "authenticated"
	}
	if v, ok := o.GetString("auth.oidc.auto_provision"); ok {
		bb, err := strconv.ParseBool(v)
		if err != nil {
			return fmt.Errorf("configbind: auth.oidc.auto_provision: %w", err)
		}
		p.OIDC.AutoProvision = bb
	} else {
		p.OIDC.AutoProvision = true
	}
	if v, ok := o.GetString("auth.oidc.claim.path"); ok {
		p.OIDC.Claim.Path = v
	}
	if v, ok := o.GetMulti("auth.oidc.claim.values"); ok {
		p.OIDC.Claim.Values = v
	}
	if v, ok := o.GetString("auth.oidc.claim.match"); ok {
		p.OIDC.Claim.Match = v
	} else {
		p.OIDC.Claim.Match = "any"
	}
	if v, ok := o.GetMulti("auth.oidc.registered_claims"); ok {
		p.OIDC.RegisteredClaims = v
	}
	if v, ok := o.GetString("auth.oidc.provider_logout"); ok {
		bb, err := strconv.ParseBool(v)
		if err != nil {
			return fmt.Errorf("configbind: auth.oidc.provider_logout: %w", err)
		}
		p.OIDC.ProviderLogout = bb
	} else {
		p.OIDC.ProviderLogout = true
	}
	if v, ok := o.GetString("auth.oidc.allow_loopback_http"); ok {
		bb, err := strconv.ParseBool(v)
		if err != nil {
			return fmt.Errorf("configbind: auth.oidc.allow_loopback_http: %w", err)
		}
		p.OIDC.AllowLoopbackHTTP = bb
	} else {
		p.OIDC.AllowLoopbackHTTP = false
	}
	return nil
}
