"use strict";

// The three surfaces LSP has no method for, drawn from this server's own
// pw/* requests: the generated Go a declaration produced, the routes a project
// serves, and where the storybook renders a component.
//
// Everything decidable without VS Code is here — how a reply is rendered and
// how a tree is shaped — so what remains in extension.js is registration.

/** The scheme the read-only generated view is published under. */
const GENERATED_SCHEME = "popcornweb-generated";

/**
 * Renders a pw/generatedFor reply as the document a reader opens.
 *
 * A status other than ok is a document too: an empty editor with no
 * explanation is the failure requirement:editor-generated-peek exists to
 * avoid, and the reason is what tells the reader to run generation.
 */
function renderGenerated(fragment) {
  if (fragment.status === "ok") {
    const header = [`// ${fragment.file}`];
    if (fragment.stale) {
      header.push(
        "// This is what the last generation produced. The source has changed since,",
        "// so run pw generate to see what it would produce now.",
      );
    }
    header.push("// Generated output: read-only, and owned by pw generate.", "");
    return header.join("\n") + fragment.text + "\n";
  }
  return [
    `// No generated code to show for ${fragment.declaration || "this position"}.`,
    `// ${fragment.message}`,
    "//",
    "// Run Popcorn Web: Generate to produce it. Nothing is generated by opening",
    "// this view, because generation writes files.",
    "",
  ].join("\n");
}

/**
 * Shapes a pw/routes reply into tree items.
 *
 * The tree is flat by design: a route's identity is its whole path, and
 * nesting `/rooms/id_` under `/rooms` would invent a parent route that serves
 * nothing.
 */
function routeItems(report) {
  return (report?.routes ?? []).map((route) => ({
    path: route.path,
    page: route.page,
    pageUri: route.pageUri,
    // The description a reader scans: which tree it came from, and whether it
    // has a handler of its own.
    description: route.handler ? `${route.root} · page.go` : route.root,
    tooltip: [
      `${route.path}`,
      `page: ${route.page}`,
      route.handler ? `handler: ${route.handler}` : "handler: generated",
      route.layouts?.length ? `layouts: ${route.layouts.join(" → ")}` : "layouts: none",
    ].join("\n"),
  }));
}

/**
 * What the route view says when it has nothing to show, which is a different
 * statement from an empty project.
 */
function routePlaceholder(report) {
  if (!report) {
    return "The language server is not running, so the routes are not known.";
  }
  if ((report.routes ?? []).length === 0) {
    return "No page tree routes. This project may register its routes in Go instead.";
  }
  return "";
}

/** The line of the view that says what it does not cover. */
function routeCaveat(report) {
  return report?.notCovered ?? "";
}

module.exports = {
  GENERATED_SCHEME,
  renderGenerated,
  routeItems,
  routePlaceholder,
  routeCaveat,
};
