// Code generated by configbind/codegen; DO NOT EDIT.

package dynamo

import (
	"fmt"
	"strconv"
	"time"

	"github.com/shibukawa/tinybind-go/cliparser"
	"github.com/shibukawa/tinybind-go/configbind"
)

func init() {
	registerConfigDefinition0()
}

func registerConfigDefinition0() {
	configbind.Register[Config](configbind.Definition{
		TypeName: "github.com/shibukawa/popcornweb/database/dynamo.Config",
		Prefix:   "middleware.dynamo",
		Doc:      "Config is the [middleware.dynamo] runtime binding. It is registered when this package is imported, so a project that does not use DynamoDB gains no key",
		KnownKeys: []string{
			"middleware.dynamo.enabled",
			"middleware.dynamo.region",
			"middleware.dynamo.endpoint",
			"middleware.dynamo.access_key_id",
			"middleware.dynamo.secret_access_key",
			"middleware.dynamo.session_token",
			"middleware.dynamo.table_prefix",
			"middleware.dynamo.table_names",
			"middleware.dynamo.timeout",
			"middleware.dynamo.max_idle_conns",
			"middleware.dynamo.verify_schema",
			"middleware.dynamo.auto_migrate",
		},
		Defaults: map[string]string{
			"middleware.dynamo.timeout":        "10s",
			"middleware.dynamo.max_idle_conns": "4",
			"middleware.dynamo.verify_schema":  "true",
		},
		Secrets: map[string]string{
			"middleware.dynamo.access_key_id":     "mask",
			"middleware.dynamo.secret_access_key": "mask",
			"middleware.dynamo.session_token":     "mask",
		},
		FlagMetas: []cliparser.FieldMeta{
			{Prefix: "middleware.dynamo", Key: "enabled", Help: "Enabled opens the client and installs the middleware", Kind: cliparser.KindBool},
			{Prefix: "middleware.dynamo", Key: "region", Help: "Region names the AWS region. Empty falls back to the environment, and a region resolvable from neither is a startup error"},
			{Prefix: "middleware.dynamo", Key: "endpoint", Help: "Endpoint overrides the regional host, which is how a local emulator is reached"},
			{Prefix: "middleware.dynamo", Key: "access_key_id", Help: "AccessKeyID and its siblings are static credentials. All three are optional; empty selects the driver's environment credentials"},
			{Prefix: "middleware.dynamo", Key: "secret_access_key"},
			{Prefix: "middleware.dynamo", Key: "session_token"},
			{Prefix: "middleware.dynamo", Key: "table_prefix", Help: "TablePrefix is prepended to a declared table name"},
			{Prefix: "middleware.dynamo", Key: "timeout", Help: "Timeout bounds one request"},
			{Prefix: "middleware.dynamo", Key: "max_idle_conns", Help: "MaxIdleConns sizes the connection pool. The rule of thumb is the expected concurrency"},
			{Prefix: "middleware.dynamo", Key: "verify_schema", Help: "VerifySchema reads every registered table once at startup and refuses to serve on a mismatch. It is the one check deployment tooling cannot make for itself, so it defaults on", Kind: cliparser.KindBool},
			{Prefix: "middleware.dynamo", Key: "auto_migrate", Help: "AutoMigrate creates missing tables during startup. It is a development convenience and is rejected elsewhere", Kind: cliparser.KindBool},
		},
		Apply: applyConfigDefinition0,
		Scaffold: []configbind.ScaffoldField{
			{Key: "enabled", Kind: configbind.ScaffoldBool, Help: "Enabled opens the client and installs the middleware"},
			{Key: "region", Kind: configbind.ScaffoldString, Help: "Region names the AWS region. Empty falls back to the environment, and a region resolvable from neither is a startup error"},
			{Key: "endpoint", Kind: configbind.ScaffoldString, Help: "Endpoint overrides the regional host, which is how a local emulator is reached"},
			{Key: "access_key_id", Kind: configbind.ScaffoldString, Help: "AccessKeyID and its siblings are static credentials. All three are optional; empty selects the driver's environment credentials"},
			{Key: "secret_access_key", Kind: configbind.ScaffoldString},
			{Key: "session_token", Kind: configbind.ScaffoldString},
			{Key: "table_prefix", Kind: configbind.ScaffoldString, Help: "TablePrefix is prepended to a declared table name"},
			{Key: "table_names", Kind: configbind.ScaffoldTableArray, Help: "TableNames maps a declared name onto a deployed one, for a name no prefix produces. An entry wins over the prefix", Nested: []configbind.ScaffoldField{
				{Key: "declared", Kind: configbind.ScaffoldString},
				{Key: "deployed", Kind: configbind.ScaffoldString},
			}},
			{Key: "timeout", Kind: configbind.ScaffoldDuration, Default: "10s", Help: "Timeout bounds one request"},
			{Key: "max_idle_conns", Kind: configbind.ScaffoldInt, Default: "4", Help: "MaxIdleConns sizes the connection pool. The rule of thumb is the expected concurrency"},
			{Key: "verify_schema", Kind: configbind.ScaffoldBool, Default: "true", Help: "VerifySchema reads every registered table once at startup and refuses to serve on a mismatch. It is the one check deployment tooling cannot make for itself, so it defaults on"},
			{Key: "auto_migrate", Kind: configbind.ScaffoldBool, Help: "AutoMigrate creates missing tables during startup. It is a development convenience and is rejected elsewhere"},
		},
	})
}

func applyConfigDefinition0(dst any, o *configbind.Overlay) error {
	p, ok := dst.(*Config)
	if !ok || p == nil {
		return fmt.Errorf("configbind: apply Config: bad destination")
	}
	if v, ok := o.GetString("middleware.dynamo.enabled"); ok {
		bb, err := strconv.ParseBool(v)
		if err != nil {
			return fmt.Errorf("configbind: middleware.dynamo.enabled: %w", err)
		}
		p.Enabled = bb
	}
	if v, ok := o.GetString("middleware.dynamo.region"); ok {
		p.Region = v
	}
	if v, ok := o.GetString("middleware.dynamo.endpoint"); ok {
		p.Endpoint = v
	}
	if v, ok := o.GetString("middleware.dynamo.access_key_id"); ok {
		p.AccessKeyID = v
	}
	if v, ok := o.GetString("middleware.dynamo.secret_access_key"); ok {
		p.SecretAccessKey = v
	}
	if v, ok := o.GetString("middleware.dynamo.session_token"); ok {
		p.SessionToken = v
	}
	if v, ok := o.GetString("middleware.dynamo.table_prefix"); ok {
		p.TablePrefix = v
	}
	if ta1, ok := o.Get("middleware.dynamo.table_names"); ok {
		if !ta1.IsTables {
			return fmt.Errorf("configbind: middleware.dynamo.table_names: expected an array of tables ([[middleware.dynamo.table_names]])")
		}
		p.TableNames = make([]TableName, len(ta1.Tables))
		for i1 := range ta1.Tables {
			if v, ok := ta1.Tables[i1].GetString("declared"); ok {
				p.TableNames[i1].Declared = v
			}
			if v, ok := ta1.Tables[i1].GetString("deployed"); ok {
				p.TableNames[i1].Deployed = v
			}
		}
	}
	if v, ok := o.GetString("middleware.dynamo.timeout"); ok {
		d, err := time.ParseDuration(v)
		if err != nil {
			return fmt.Errorf("configbind: middleware.dynamo.timeout: %w", err)
		}
		p.Timeout = d
	} else {
		p.Timeout = 10000000000 // 10s
	}
	if v, ok := o.GetString("middleware.dynamo.max_idle_conns"); ok {
		n, err := strconv.ParseInt(v, 10, 0)
		if err != nil {
			return fmt.Errorf("configbind: middleware.dynamo.max_idle_conns: %w", err)
		}
		p.MaxIdleConns = int(n)
	} else {
		p.MaxIdleConns = 4
	}
	if v, ok := o.GetString("middleware.dynamo.verify_schema"); ok {
		bb, err := strconv.ParseBool(v)
		if err != nil {
			return fmt.Errorf("configbind: middleware.dynamo.verify_schema: %w", err)
		}
		p.VerifySchema = bb
	} else {
		p.VerifySchema = true
	}
	if v, ok := o.GetString("middleware.dynamo.auto_migrate"); ok {
		bb, err := strconv.ParseBool(v)
		if err != nil {
			return fmt.Errorf("configbind: middleware.dynamo.auto_migrate: %w", err)
		}
		p.AutoMigrate = bb
	}
	return nil
}
