// Code generated by httpbinder; DO NOT EDIT.

package main

import (
	"encoding/json"
	"net/http"

	"github.com/shibukawa/httpbind-go"
)

type jsonRaw = json.RawMessage

func init() {
	httpbinder.RegisterBind[EchoRequest](bindEchoRequest)
	httpbinder.RegisterWrite[EchoRequest](writeEchoRequest)
	httpbinder.RegisterBind[EchoResponse](bindEchoResponse)
	httpbinder.RegisterWrite[EchoResponse](writeEchoResponse)
}

func bindEchoRequest(r *http.Request) (EchoRequest, error) {
	var out EchoRequest
	var presentMessage bool
	var presentCount bool
	var jsonBody map[string]jsonRaw
	var formBody map[string]string
	var bodyRead bool
	readBody := func() error {
		if bodyRead {
			return nil
		}
		bodyRead = true
		if httpbinder.IsJSONRequest(r) {
			m, err := httpbinder.ReadJSONMap(r)
			if err != nil {
				return err
			}
			jsonBody = m
			return nil
		}
		if httpbinder.IsFormRequest(r) {
			m, err := httpbinder.ParseFormMap(r)
			if err != nil {
				return err
			}
			formBody = m
			return nil
		}
		if httpbinder.IsMultipartRequest(r) {
			m, _, err := httpbinder.ParseMultipartMap(r)
			if err != nil {
				return err
			}
			formBody = m
			return nil
		}
		return nil
	}
	if err := readBody(); err != nil {
		return out, err
	}
	if raw, ok := jsonBody["message"]; ok {
		presentMessage = true
		v, err := httpbinder.DecodeJSONString(raw)
		if err != nil {
			return out, httpbinder.BindError("message", "payload", "invalid string")
		}
		out.Message = v
	} else if formBody != nil {
		if fv, ok := formBody["message"]; ok {
			presentMessage = true
			out.Message = fv
		}
	}
	if err := readBody(); err != nil {
		return out, err
	}
	if raw, ok := jsonBody["count"]; ok {
		presentCount = true
		v, err := httpbinder.DecodeJSONInt(raw)
		if err != nil {
			return out, httpbinder.BindError("count", "payload", "invalid int")
		}
		out.Count = v
	} else if formBody != nil {
		if fv, ok := formBody["count"]; ok {
			presentCount = true
			v, err := httpbinder.ParseInt(fv)
			if err != nil {
				return out, httpbinder.BindError("count", "payload", "invalid int")
			}
			out.Count = v
		}
	}
	var checkFields []httpbinder.FieldError
	if !presentMessage || out.Message == "" {
		checkFields = append(checkFields, httpbinder.Field("message", "payload", "required"))
	}
	if presentMessage {
		if len(out.Message) < 1 {
			checkFields = append(checkFields, httpbinder.Field("message", "payload", "length must be >= 1"))
		}
		if len(out.Message) > 128 {
			checkFields = append(checkFields, httpbinder.Field("message", "payload", "length must be <= 128"))
		}
	}
	if !presentCount {
		checkFields = append(checkFields, httpbinder.Field("count", "payload", "required"))
	}
	if presentCount {
		if out.Count < 1 {
			checkFields = append(checkFields, httpbinder.Field("count", "payload", "must be >= 1"))
		}
		if out.Count > 10 {
			checkFields = append(checkFields, httpbinder.Field("count", "payload", "must be <= 10"))
		}
	}
	if len(checkFields) > 0 {
		return out, httpbinder.Validation(checkFields...)
	}
	return out, nil
}

func writeEchoRequest(w http.ResponseWriter, r *http.Request, v EchoRequest) error {
	_ = r
	body := map[string]any{
		"message": v.Message,
		"count":   v.Count,
	}
	return httpbinder.WriteJSON(w, http.StatusOK, body)
}

func bindEchoResponse(r *http.Request) (EchoResponse, error) {
	var out EchoResponse
	var jsonBody map[string]jsonRaw
	var formBody map[string]string
	var bodyRead bool
	readBody := func() error {
		if bodyRead {
			return nil
		}
		bodyRead = true
		if httpbinder.IsJSONRequest(r) {
			m, err := httpbinder.ReadJSONMap(r)
			if err != nil {
				return err
			}
			jsonBody = m
			return nil
		}
		if httpbinder.IsFormRequest(r) {
			m, err := httpbinder.ParseFormMap(r)
			if err != nil {
				return err
			}
			formBody = m
			return nil
		}
		if httpbinder.IsMultipartRequest(r) {
			m, _, err := httpbinder.ParseMultipartMap(r)
			if err != nil {
				return err
			}
			formBody = m
			return nil
		}
		return nil
	}
	if qv, ok := httpbinder.QueryValue(r, "message"); ok {
		out.Message = qv
	} else {
		if err := readBody(); err != nil {
			return out, err
		}
		if raw, ok := jsonBody["message"]; ok {
			v, err := httpbinder.DecodeJSONString(raw)
			if err != nil {
				return out, httpbinder.BindError("message", "payload", "invalid string")
			}
			out.Message = v
		} else if formBody != nil {
			if fv, ok := formBody["message"]; ok {
				out.Message = fv
			}
		}
	}
	if qv, ok := httpbinder.QueryValue(r, "count"); ok {
		v, err := httpbinder.ParseInt(qv)
		if err != nil {
			return out, httpbinder.BindError("count", "query", "invalid int")
		}
		out.Count = v
	} else {
		if err := readBody(); err != nil {
			return out, err
		}
		if raw, ok := jsonBody["count"]; ok {
			v, err := httpbinder.DecodeJSONInt(raw)
			if err != nil {
				return out, httpbinder.BindError("count", "payload", "invalid int")
			}
			out.Count = v
		} else if formBody != nil {
			if fv, ok := formBody["count"]; ok {
				v, err := httpbinder.ParseInt(fv)
				if err != nil {
					return out, httpbinder.BindError("count", "payload", "invalid int")
				}
				out.Count = v
			}
		}
	}
	if qv, ok := httpbinder.QueryValue(r, "source"); ok {
		out.Source = qv
	} else {
		if err := readBody(); err != nil {
			return out, err
		}
		if raw, ok := jsonBody["source"]; ok {
			v, err := httpbinder.DecodeJSONString(raw)
			if err != nil {
				return out, httpbinder.BindError("source", "payload", "invalid string")
			}
			out.Source = v
		} else if formBody != nil {
			if fv, ok := formBody["source"]; ok {
				out.Source = fv
			}
		}
	}
	return out, nil
}

func writeEchoResponse(w http.ResponseWriter, r *http.Request, v EchoResponse) error {
	_ = r
	body := map[string]any{
		"message": v.Message,
		"count":   v.Count,
		"source":  v.Source,
	}
	return httpbinder.WriteJSON(w, http.StatusOK, body)
}
