// Code generated by Popcorn Wave via TinyBind; DO NOT EDIT.

package main

import (
	"encoding/json"
	"fmt"

	"github.com/shibukawa/tinybind-go"
	"github.com/shibukawa/tinybind-go/cliparser"
	"github.com/shibukawa/tinybind-go/configbind"

	"github.com/shibukawa/tinybind-go/jsonbind"
	"io"
	"net/http"
)

func init() {
	httpbind.RegisterBind[EchoRequest](bindEchoRequest)
	httpbind.RegisterWrite[EchoResponse](writeEchoResponse)
}

func decodeEchoRequestBytes(data []byte) (EchoRequest, error) {
	return decodeEchoRequestJSON(json.RawMessage(data))
}

func decodeEchoRequestJSON(raw json.RawMessage) (EchoRequest, error) {
	var out EchoRequest
	m, err := jsonbind.RawJSONMap(raw)
	if err != nil {
		return out, err
	}
	if raw, ok := m["message"]; ok {
		v, err := jsonbind.DecodeJSONString(raw)
		if err != nil {
			return out, jsonbind.FieldError("message", "invalid string", err)
		}
		out.Message = v
	}
	if raw, ok := m["count"]; ok {
		v, err := jsonbind.DecodeJSONInt(raw)
		if err != nil {
			return out, jsonbind.FieldError("count", "invalid int", err)
		}
		out.Count = v
	}
	return out, nil
}

func bindEchoRequest(r *http.Request) (EchoRequest, error) {
	var out EchoRequest
	var presentMessage bool
	var presentCount bool
	var jsonBody map[string]json.RawMessage
	var formBody map[string]string
	var bodyRead bool
	readBody := func() error {
		if bodyRead {
			return nil
		}
		bodyRead = true
		if httpbind.IsJSONRequest(r) {
			m, err := httpbind.ReadJSONMap(r)
			if err != nil {
				return err
			}
			jsonBody = m
			return nil
		}
		if httpbind.IsFormRequest(r) {
			m, err := httpbind.ParseFormMap(r)
			if err != nil {
				return err
			}
			formBody = m
			return nil
		}
		if httpbind.IsMultipartRequest(r) {
			m, _, err := httpbind.ParseMultipartMap(r)
			if err != nil {
				return err
			}
			formBody = m
			return nil
		}
		return nil
	}
	if err := readBody(); err != nil {
		return out, err
	}
	if raw, ok := jsonBody["message"]; ok {
		presentMessage = true
		v, err := jsonbind.DecodeJSONString(raw)
		if err != nil {
			return out, jsonbind.FieldError("message", "invalid string", err)
		}
		out.Message = v
	} else if formBody != nil {
		if fv, ok := formBody["message"]; ok {
			presentMessage = true
			out.Message = fv
		}
	}
	if err := readBody(); err != nil {
		return out, err
	}
	if raw, ok := jsonBody["count"]; ok {
		presentCount = true
		v, err := jsonbind.DecodeJSONInt(raw)
		if err != nil {
			return out, jsonbind.FieldError("count", "invalid int", err)
		}
		out.Count = v
	} else if formBody != nil {
		if fv, ok := formBody["count"]; ok {
			presentCount = true
			v, err := httpbind.ParseInt(fv)
			if err != nil {
				return out, httpbind.BindError("count", "payload", "invalid int")
			}
			out.Count = v
		}
	}
	var checkFields []httpbind.FieldError
	if !presentMessage || out.Message == "" {
		checkFields = append(checkFields, httpbind.Field("message", "payload", "required"))
	}
	if presentMessage {
		if len(out.Message) < 1 {
			checkFields = append(checkFields, httpbind.Field("message", "payload", "length must be >= 1"))
		}
		if len(out.Message) > 128 {
			checkFields = append(checkFields, httpbind.Field("message", "payload", "length must be <= 128"))
		}
	}
	if !presentCount {
		checkFields = append(checkFields, httpbind.Field("count", "payload", "required"))
	}
	if presentCount {
		if out.Count < 1 {
			checkFields = append(checkFields, httpbind.Field("count", "payload", "must be >= 1"))
		}
		if out.Count > 10 {
			checkFields = append(checkFields, httpbind.Field("count", "payload", "must be <= 10"))
		}
	}
	if len(checkFields) > 0 {
		return out, httpbind.Validation(checkFields...)
	}
	return out, nil
}

func encodeEchoResponseMap(v EchoResponse) map[string]any {
	body := map[string]any{}
	body["message"] = v.Message
	body["count"] = v.Count
	body["source"] = v.Source
	return body
}

func encodeEchoResponse(w io.Writer, v EchoResponse) error {
	return json.NewEncoder(w).Encode(encodeEchoResponseMap(v))
}

func writeEchoResponse(w http.ResponseWriter, r *http.Request, v EchoResponse) error {
	_ = r
	return httpbind.WriteJSON(w, http.StatusOK, encodeEchoResponseMap(v))
}
func init() {
	registerGenerateConfigCommandDefinition0()
}

func registerGenerateConfigCommandDefinition0() {
	configbind.RegisterSubCommand[GenerateConfigCommand](configbind.SubCommandDefinition{
		TypeName:  "github.com/shibukawa/popcornwave/examples/httpserver.GenerateConfigCommand",
		Name:      "generate-config",
		Help:      "write merged configuration scaffolds",
		FlagMetas: []cliparser.FieldMeta{},
		Positionals: []configbind.Positional{
			{ConfigKey: "format", Name: "format", Role: configbind.PositionalRequired, Help: "output format: toml or env"},
		},
		Apply: applyGenerateConfigCommandDefinition0,
	})
}

func applyGenerateConfigCommandDefinition0(dst any, o *configbind.Overlay) error {
	p, ok := dst.(*GenerateConfigCommand)
	if !ok || p == nil {
		return fmt.Errorf("configbind: apply GenerateConfigCommand: bad destination")
	}
	if v, ok := o.GetString("format"); ok {
		p.Format = v
	}
	return nil
}
